/**
 * Hangman word dictionary for Mi Band 9 Pro
 *
 * Each entry: { word: string, hint: string }
 * Words are 4-7 letters, common English vocabulary.
 */
var wordList = [
  { word: 'APPLE', hint: '一种水果' },
  { word: 'HOUSE', hint: '居住的建筑' },
  { word: 'WATER', hint: '每天都要喝的' },
  { word: 'CLOUD', hint: '在天上飘的' },
  { word: 'DREAM', hint: '睡觉时发生的' },
  { word: 'MUSIC', hint: '用耳朵欣赏的' },
  { word: 'RIVER', hint: '流动的水' },
  { word: 'TIGER', hint: '有条纹的大猫' },
  { word: 'PAPER', hint: '写字用的' },
  { word: 'CLOCK', hint: '告诉我们时间' },
  { word: 'STONE', hint: '很硬的天然物' },
  { word: 'HONEY', hint: '蜜蜂生产的甜东西' },
  { word: 'LIGHT', hint: '太阳发出的' },
  { word: 'FLOWER', hint: '花园里漂亮的植物' },
  { word: 'BRIDGE', hint: '连接河两岸' },
  { word: 'PLANET', hint: '地球就是一颗' },
  { word: 'GARDEN', hint: '种花种菜的地方' },
  { word: 'WINTER', hint: '最冷的季节' },
  { word: 'SUMMER', hint: '最热的季节' },
  { word: 'ORANGE', hint: '一种颜色，也是一种水果' },
  { word: 'PURPLE', hint: '红色加蓝色的颜色' },
  { word: 'SILVER', hint: '贵重的白色金属' },
  { word: 'BUTTER', hint: '抹在面包上的' },
  { word: 'CANDLE', hint: '点火照明的' },
  { word: 'DINNER', hint: '晚上吃的那顿饭' },
  { word: 'FAMILY', hint: '爸爸妈妈和你' },
  { word: 'GUIDE', hint: '带路的人' },
  { word: 'HEAVEN', hint: '天空，也指极乐世界' },
  { word: 'ISLAND', hint: '被水包围的陆地' },
  { word: 'JUNGLE', hint: '茂密的森林' },
  { word: 'KITTEN', hint: '小猫咪' },
  { word: 'LEMON', hint: '很酸的水果' },
  { word: 'MONKEY', hint: '聪明的动物，爱吃香蕉' },
  { word: 'NATURE', hint: '大自然' },
  { word: 'PILLOW', hint: '睡觉时垫头的' },
  { word: 'QUIET', hint: '没有声音' },
  { word: 'ROCKET', hint: '飞向太空的' },
  { word: 'SALAD', hint: '一种凉拌菜' },
  { word: 'TEMPLE', hint: '烧香拜佛的地方' },
  { word: 'VACUUM', hint: '没有空气的空间' },
  { word: 'WINDOW', hint: '墙上的透明部分' },
  { word: 'BASKET', hint: '用来装东西的编织容器' },
  { word: 'COTTON', hint: '做衣服的白色植物纤维' },
  { word: 'DONKEY', hint: '像马的动物，叫声很响' },
  { word: 'EAGLE', hint: '一种大型猛禽' },
  { word: 'FRIDGE', hint: '冷藏食物的电器' },
  { word: 'GINGER', hint: '有辣味的根茎调料' },
  { word: 'HUNTER', hint: '打猎的人' },
  { word: 'LAUNDRY', hint: '洗衣服的地方' },
  { word: 'MIRROR', hint: '照出你自己的' },
  { word: 'NECKLACE', hint: '戴在脖子上的饰品' },
  { word: 'PENGUIN', hint: '不会飞的南极鸟' },
  { word: 'RAINBOW', hint: '雨后天空的彩带' },
  { word: 'SAILOR', hint: '在船上工作的人' },
  { word: 'THUNDER', hint: '闪电后巨大的响声' },
  { word: 'VELVET', hint: '一种柔软光滑的布料' },
  { word: 'CARROT', hint: '兔子爱吃的橙色蔬菜' },
  { word: 'PUZZLE', hint: '需要动脑解决的' },
  { word: 'SUNSET', hint: '太阳下山的时候' },
  { word: 'BUTTON', hint: '衣服上的小圆片' }
]

module.exports = wordList