/**
 * 3200 words — compact flat format [word,hint,word,hint,...]
 */
var wordList = [
  'ABANDON',
  'v. 抛弃，舍弃，放弃',
  'ABILITY',
  'n. 能力；才能',
  'ABLE',
  'a. 能够；有能力的',
  'ABOARD',
  'prep. 上（船，飞机，火车，汽车等）',
  'ABOLISH',
  'v. 废除，废止',
  'ABOUT',
  'prep. 关于；在各处；四处',
  'ABOVE',
  'prep. 在……上面',
  'ABROAD',
  'ad. 到（在）国外',
  'ABRUPT',
  'a. 突然的，意外的，粗鲁的',
  'ABSENCE',
  'n. 不在，缺席',
  'ABSENT',
  'a. 缺席，不在',
  'ABSORB',
  'v. 吸收，使全神贯注',
  'ABSURD',
  'a. 荒谬的，怪诞不经的',
  'ABUSE',
  'v. 滥用，虐待，恶语',
  'ACADEMY',
  'n. 专科学院，（美）私立学校',
  'ACCENT',
  'n. 口音，音调',
  'ACCEPT',
  'v. 接受',
  'ACCESS',
  'n. 通道，入径，存取（计算机文件）',
  'ACCOUNT',
  'n. 账目；描述',
  'ACCUSE',
  'v. 控告，指控，指责',
  'ACHE',
  'vi. & n. 痛，疼痛',
  'ACHIEVE',
  'vt. 达到，取得',
  'ACID',
  'a. 酸的',
  'ACQUIRE',
  'v. 获得，得到',
  'ACRE',
  'n. 英亩',
  'ACROSS',
  'prep. 横过，穿过',
  'ACTION',
  'n. 行动',
  'ACTIVE',
  'a. 积极的，主动的',
  'ACTOR',
  'n. 男演员',
  'ACTRESS',
  'n. 女演员',
  'ACTUAL',
  'a. 实际的；现实的',
  'ACUTE',
  'a. 十分严重的，（病）急性的',
  'ADAPT',
  'v. 使适应，适合，改编',
  'ADDRESS',
  'n. 地址',
  'ADJUST',
  'v. 调整，调节，适应，习惯',
  'ADMIRE',
  'v. 钦佩；羡慕',
  'ADMIT',
  'vt. 承认，准许（入场，入学，入会）',
  'ADOPT',
  'v. 收养，领养',
  'ADORE',
  'v. （不用于进行时）热爱，爱慕某人',
  'ADULT',
  'n. 成年人',
  'ADVANCE',
  'v. 推进，促进；前进',
  'ADVICE',
  'n. 忠告，劝告，建议',
  'ADVISE',
  'vt. 忠告，劝告，建议',
  'AFFAIR',
  'n. 事，事情',
  'AFFECT',
  'vt. 影响',
  'AFFORD',
  'vt. 负担得起（……的费用）；抽得出（时间）；提供',
  'AFRAID',
  'a. 害怕的；担心',
  'AFRICA',
  'n. 非洲',
  'AFRICAN',
  'a. 非洲的，非洲人的',
  'AFTER',
  'prep. 在…之后；在 后面',
  'AGAIN',
  'ad. 再一次；再，又',
  'AGAINST',
  'prep. 对着，反对',
  'AGENCY',
  'n. 代理机构',
  'AGENDA',
  'n. （会议）议程表，议事日程',
  'AGENT',
  'n. 代理人，经纪人',
  'AGREE',
  'v. 同意；应允',
  'AHEAD',
  'ad. 在前，向前',
  'AIDS',
  'n. 艾滋病',
  'AIRLINE',
  'n. 航空公司；航空系统',
  'AIRMAIL',
  'n. 航空邮件',
  'AIRPORT',
  'n. 航空站，飞机场',
  'ALARM',
  'n. 警报',
  'ALBUM',
  'n. 相册，影集，集邮簿',
  'ALCOHOL',
  'n. 含酒精饮料，酒',
  'ALGEBRA',
  'n. 代数',
  'ALIKE',
  'a. 相似的，相同的',
  'ALIVE',
  'a. 活着的，存在的',
  'ALLEY',
  'n. 小巷，胡同',
  'ALLOW',
  'vt. 允许，准许',
  'ALMOST',
  'ad. 几乎，差不多',
  'ALONE',
  'a. 单独的，孤独的',
  'ALONG',
  'prep. 沿着；顺着',
  'ALOUD',
  'ad. 大声地',
  'ALREADY',
  'ad. 已经',
  'ALSO',
  'ad. 也',
  'ALWAYS',
  'ad. 总是；一直；永远',
  'AMATEUR',
  'a. 业余爱好的',
  'AMAZE',
  'v. 惊奇，惊叹；震惊',
  'AMAZING',
  'a. 令人惊奇的，惊叹的；震惊的',
  'AMERICA',
  'n. 美国；美洲',
  'AMONG',
  'prep. 在…中间；在（三个以上）之间',
  'AMOUNT',
  'n. 金额，数量，总计',
  'AMPLE',
  'a. 足够的，丰裕的',
  'AMUSE',
  'vt. （使人）快乐，逗乐',
  'ANALYZE',
  'v. 分析',
  'ANCHOR',
  'n. 锚；主持人',
  'ANCIENT',
  'a. 古代的，古老的',
  'ANGER',
  'n. 怒，愤怒',
  'ANGLE',
  'n. 角度',
  'ANGRY',
  'a. 生气的，愤怒的',
  'ANIMAL',
  'n. 动物',
  'ANKLE',
  'n. 踝，踝关节',
  'ANNOY',
  'vt. （使）烦恼',
  'ANNUAL',
  'a. 每年的，年度的，一年一次的',
  'ANOTHER',
  'a. 再一；另一；别的；不同的',
  'ANSWER',
  'v. 回答，答复；回信；（作出）答案',
  'ANTIQUE',
  'n. 古董',
  'ANXIETY',
  'n. 担忧，焦虑',
  'ANXIOUS',
  'a. 忧虑的，焦急的',
  'ANYBODY',
  'pron. 任何人，无论谁',
  'ANYHOW',
  'ad. 不管怎样',
  'ANYONE',
  'pron. 任何人，无论谁',
  'ANYWAY',
  'ad. 不管怎样',
  'APART',
  'ad./a. 相隔，相距，除外',
  'APOLOGY',
  'n. 道歉；歉意',
  'APPEAL',
  'v. 上诉，申诉',
  'APPEAR',
  'vi. 出现',
  'APPLAUD',
  'v. 鼓掌，赞许，赞赏',
  'APPLE',
  'n. 苹果',
  'APPLY',
  'v. 申请',
  'APPOINT',
  'v. 任命，委任，安排，确定（时间，地点）',
  'APPROVE',
  'v. 赞成，同意，批准，通过',
  'APRON',
  'n. （机场的）停机坪',
  'ARCH',
  'n. 拱，拱门',
  'APRIL',
  'n. 4月',
  'ARAB',
  'a. 阿拉伯的',
  'ARABIC',
  'a. 阿拉伯语的',
  'ARCTIC',
  'a. 北极的',
  'AREA',
  'n. 面积；地域，地方，区域；范围，领域',
  'ARGUE',
  'vi. 争辩，争论',
  'ARISE',
  'vi. 起来，升起；出现',
  'ARMY',
  'n. 军队',
  'AROUND',
  'ad. 在周围；在附近',
  'ARRANGE',
  'v. 安排，布置',
  'ARREST',
  'v. 逮捕，拘留',
  'ARRIVAL',
  'n. 到来，到达',
  'ARRIVE',
  'vi. 到达；达到',
  'ARROW',
  'n. 箭；箭头',
  'ARTICLE',
  'n. 文章；东西，物品；冠词',
  'ARTIST',
  'n. 艺术家',
  'ASHAMED',
  'a. 惭愧；害臊',
  'ASIA',
  'n. 亚洲',
  'ASIAN',
  'a. 亚洲（人）的',
  'ASIDE',
  'ad. 在旁边',
  'ASLEEP',
  'a. 睡着的，熟睡',
  'ASPECT',
  'n. 方面，外观，外表',
  'ASSESS',
  'v. 评价，评定（性质，质量）',
  'ASSIST',
  'v. 帮助，协助',
  'ASSUME',
  'v. 假定，假设',
  'ATHLETE',
  'n. 运动员',
  'ATOM',
  'n. 原子，微粒',
  'ATTACH',
  'v. 把…固定，重视',
  'ATTACK',
  'v./n. 攻击，袭击',
  'ATTAIN',
  'v.（经过努力）获得，得到',
  'ATTEMPT',
  'vt. 试图，尝试',
  'ATTEND',
  'v. 看护，照料，服侍；出席，参加',
  'ATTRACT',
  'v. 吸引，引起',
  'AUTHOR',
  'n. 作者，作家；创造者，发起人',
  'AUGUST',
  'n. 八月',
  'AUNT',
  'n. 伯母，舅母，婶母，姑母，姨母',
  'AUTUMN',
  'n. 秋天，秋季',
  'AVENUE',
  'n. 林荫大道，大街；途径，手段',
  'AVERAGE',
  'n. 平均数，平均水平 a. 平均的，普通的',
  'AVOID',
  'v. 避免，躲开，逃避',
  'AWAKE',
  'a. 醒着的 v. 唤醒，使觉醒 (awoke, awoken)',
  'AWARD',
  'n. 奖品，奖金 v. 授予，给予',
  'AWARE',
  'a. 知道的，意识到的',
  'AWAY',
  'ad. 离开，远离；消失',
  'AWESOME',
  'a. 令人惊叹的，极好的；很困难的',
  'AWFUL',
  'a. 极坏的，糟糕的；可怕的，令人敬畏的',
  'AWKWARD',
  'a. 尴尬的，棘手的；笨拙的，不便的',
  'BABY',
  'n. 婴儿，宝贝；幼小动物 a. 幼小的',
  'BACK',
  'n. 背部，后面 ad. 向后，回原处 a. 后面的 v. 支持，后退',
  'BACON',
  'n. 咸猪肉，熏猪肉',
  'BADLY',
  'ad. 坏地，严重地；非常',
  'BAGGAGE',
  'n. 行李 (美)',
  'BAKE',
  'v. 烤，烘烤；晒干',
  'BAKERY',
  'n. 面包店，烘焙店',
  'BALANCE',
  'n. 平衡，余额；天平 v. 使平衡',
  'BALCONY',
  'n. 阳台，露台；楼座',
  'BALL',
  'n. 球，球状物；舞会',
  'BALLET',
  'n. 芭蕾舞，芭蕾舞剧',
  'BALLOON',
  'n. 气球',
  'BAMBOO',
  'n. 竹，竹子',
  'BANANA',
  'n. 香蕉',
  'BAND',
  'n. 乐队，带子，波段；一群',
  'BANDAGE',
  'n. 绷带 v. 用绷带包扎',
  'BANG',
  'int. 砰 n. 巨响，猛击 v. 猛敲，砰地关上',
  'BANK',
  'n. 银行；河岸；堤；库',
  'BARBER',
  'n. 理发师 (男)',
  'BARE',
  'a. 裸露的，光秃秃的；空的，仅有的',
  'BARGAIN',
  'n. 便宜货，特价商品；交易 v. 讨价还价',
  'BARK',
  'v. 狗叫 n. 树皮；吠声',
  'BARRIER',
  'n. 障碍，屏障；栅栏',
  'BASE',
  'n. 基础，底座；基地；总部 v. 以…为基础',
  'BASIC',
  'a. 基本的，基础的；初步的',
  'BASIN',
  'n. 盆地，流域；水盆，洗脸盆',
  'BASIS',
  'n. 基础，根据；原则 (复数 bases)',
  'BASKET',
  'n. 篮子，筐',
  'BATH',
  'n. 洗澡，沐浴；浴缸 v. 给…洗澡',
  'BATHE',
  'v. 洗澡，游泳；浸洗，冲刷',
  'BATHTUB',
  'n. 浴缸，澡盆',
  'BATTERY',
  'n. 电池，蓄电池；排炮',
  'BATTLE',
  'n. 战斗，战役；斗争 v. 搏斗，奋斗',
  'BEACH',
  'n. 海滩，海滨',
  'BEAM',
  'n. 梁，横梁；光束，射线；平衡木 v. 发射，微笑',
  'BEAN',
  'n. 豆，豆科植物；豆子',
  'BEAR',
  'v. 忍受，承受；生育，结果实 n. 熊',
  'BEARD',
  'n. 胡须，络腮胡子',
  'BEAST',
  'n. 野兽，牲畜；凶残的人',
  'BEAT',
  'v. 打，敲击；打败；心跳 n. 节拍 (beat, beaten)',
  'BEAUTY',
  'n. 美丽，美人；优点',
  'BECAUSE',
  'conj. 因为，由于',
  'BECOME',
  'v. 成为，变得 (became, become)',
  'BEDROOM',
  'n. 卧室，寝室',
  'BEEF',
  'n. 牛肉；抱怨',
  'BEEHIVE',
  'n. 蜂箱，蜂巢',
  'BEER',
  'n. 啤酒',
  'BEFORE',
  'prep. 在…之前；在…前面 conj. 在…以前 ad. 以前',
  'BEGIN',
  'v. 开始，着手；起始 (began, begun)',
  'BEHALF',
  'n. 代表某人，为了某人',
  'BEHAVE',
  'v. 表现，举止；守规矩',
  'BEHIND',
  'prep. 在…后面 ad. 在后面；落后',
  'BEING',
  'n. 存在；生物；人',
  'BELGIUM',
  'n. 比利时（国家名）',
  'BELIEF',
  'n. 信念，信仰；相信',
  'BELIEVE',
  'v. 相信；认为',
  'BELL',
  'n. 钟，铃；钟声',
  'BELLY',
  'n. 肚子，腹部；胃',
  'BELONG',
  'v. 属于，附属；适合',
  'BELOW',
  'prep. 在…下面 ad. 在下方',
  'BELT',
  'n. 腰带，皮带；地带',
  'BENCH',
  'n. 长凳；工作台；法官席',
  'BEND',
  'v. 弯曲，弯腰 (bent, bent) n. 弯曲处',
  'BENEATH',
  'prep. 在…下方；低于 ad. 在下面',
  'BENEFIT',
  'n. 利益，好处；福利 v. 有益于',
  'BENT',
  'a. 弯曲的；决意的 n. 天赋，倾向',
  'BESIDE',
  'prep. 在…旁边；与…相比',
  'BESIDES',
  'prep. 除…之外 ad. 此外，而且',
  'BEST',
  'a. & ad. 最好的（地） n. 最好的事物',
  'BETTER',
  'a. & ad. 更好的（地） v. 改善，超过 n. 较好者',
  'BETRAY',
  'v. 背叛，出卖；泄露（秘密）',
  'BETWEEN',
  'prep. 在（两者）之间；在…中间',
  'BEYOND',
  'prep. 在…那边；超出 ad. 在更远处',
  'BICYCLE',
  'n. 自行车 v. 骑自行车',
  'BIKE',
  'n. 自行车 (bicycle的简称)',
  'BILL',
  'n. 账单；议案；钞票；票据',
  'BILLION',
  'num. 十亿，百亿',
  'BINGO',
  'n. 宾戈游戏；int. 太好了！',
  'BIOLOGY',
  'n. 生物学',
  'BIRD',
  'n. 鸟，禽',
  'BIRTH',
  'n. 出生，诞生；起源',
  'BISCUIT',
  'n. 饼干；小点心',
  'BISHOP',
  'n. 主教；（国际象棋）象',
  'BITE',
  'v. 咬，叮 (bit, bitten) n. 咬，一口',
  'BITTER',
  'a. 苦的；痛苦的；尖锐的',
  'BLACK',
  'a. 黑色的；黑暗的 n. 黑色',
  'BLAME',
  'n. & v. 责备，责怪',
  'BLANK',
  'a. 空白的；茫然的 n. 空白处',
  'BLANKET',
  'n. 毛毯，毯子；覆盖层',
  'BLEED',
  'v. 出血，流血 (bled, bled)',
  'BLESS',
  'v. 祝福，保佑 (blessed, blessed 或 blest)',
  'BLIND',
  'a. 瞎的；盲目的 v. 使失明 n. 窗帘',
  'BLOCK',
  'n. 块；街区；障碍物 v. 阻塞，阻挡',
  'BLOOD',
  'n. 血，血液；血统',
  'BLOUSE',
  'n. 宽松上衣，女衬衫',
  'BLOW',
  'n. 击打，打击',
  'BLUE',
  'a. 蓝色的；忧郁的 n. 蓝色',
  'BOARD',
  'n. 木板；委员会；董事会；板 v. 上船/火车/飞机',
  'BOAT',
  'n. 小船，小舟',
  'BOATING',
  'n. 划船，泛舟',
  'BODY',
  'n. 身体；尸体；主体；团体',
  'BOIL',
  'v. 沸腾；煮；烧开 n. 沸点',
  'BOMB',
  'n. 炸弹 v. 轰炸',
  'BOND',
  'n. 纽带，联系；债券；结合 v. 建立联系',
  'BONE',
  'n. 骨头，骨骼',
  'BONUS',
  'n. 奖金，红利；额外好处',
  'BOOK',
  'n. 书；本子 v. 预订，登记',
  'BOOM',
  'n. 繁荣，激增；轰鸣声 v. 激增，发出轰鸣',
  'BOOT',
  'n. 靴子；（汽车）行李箱 v. 踢',
  'BOOTH',
  'n. 小亭，电话亭；隔间',
  'BORDER',
  'n. 边界，边境；边缘 v. 接壤',
  'BORED',
  'a. 厌倦的，烦闷的',
  'BORING',
  'a. 乏味的，无聊的',
  'BORN',
  'a. 出生的；天生的',
  'BORROW',
  'v. 借入，借用',
  'BOSS',
  'n. 老板，上司 v. 指挥',
  'BOTANY',
  'n. 植物学',
  'BOTH',
  'a. & pron. 两者，双方',
  'BOTTLE',
  'n. 瓶子 v. 装瓶',
  'BOTTOM',
  'n. 底部，底；末尾 a. 最底的',
  'BOUNCE',
  'v. 弹起，反弹；跳跃 n. 弹跳',
  'BOUND',
  'a. 被束缚的；一定的 v. 跳跃；限制',
  'BOWL',
  'n. 碗，钵； bowl of soup 一碗汤',
  'BOWLING',
  'n. 保龄球运动',
  'BOXING',
  'n. 拳击运动',
  'BOYCOTT',
  'v./ n. 抵制，拒绝购买',
  'BRAIN',
  'n. 大脑；智力；头脑',
  'BRAKE',
  'n. 刹车，制动器 v. 刹车',
  'BRANCH',
  'n. 树枝；分支；分公司；分店',
  'BRAND',
  'n. 品牌；商标；烙印 v. 打烙印；铭刻',
  'BRAVE',
  'a. 勇敢的，无畏的 v. 勇敢面对',
  'BRAVERY',
  'n. 勇敢，勇气',
  'BREAD',
  'n. 面包；生计',
  'BREAK',
  'v. 打破；折断；损坏；中断 n. 休息；破裂',
  'BREAST',
  'n. 乳房；胸部；胸脯',
  'BREATH',
  'n. 呼吸；气息',
  'BREATHE',
  'v. 呼吸；吸入',
  'BREWERY',
  'n. 啤酒厂；酿酒厂',
  'BRICK',
  'n. 砖；积木',
  'BRIDE',
  'n. 新娘',
  'BRIDGE',
  'n. 桥；桥梁；桥牌 v. 架桥；弥合',
  'BRIEF',
  'a. 简洁的；短暂的 n. 摘要；简报 v. 简要介绍',
  'BRIGHT',
  'a. 明亮的；聪明的；鲜艳的',
  'BRING',
  'v. 带来；拿来；引起',
  'BRITAIN',
  'n. 英国；不列颠',
  'BRITISH',
  'a. 英国的；英国人的',
  'BROAD',
  'a. 宽阔的；广泛的；概括的',
  'BROKEN',
  'a. 破碎的；损坏的；心碎的',
  'BROOM',
  'n. 扫帚',
  'BROTHER',
  'n. 兄弟；同胞',
  'BROWN',
  'a. 棕色的；褐色的 n. 棕色',
  'BRUNCH',
  'n. 早午餐（晚早饭）',
  'BRUSH',
  'n. 刷子；画笔 v. 刷；拂过',
  'BUCKET',
  'n. 水桶；一桶',
  'BUDGET',
  'n. 预算 v. 安排预算 a. 廉价的',
  'BUFFET',
  'n. 自助餐',
  'BUILD',
  'v. 建造；建立；建设',
  'BUNCH',
  'n. 一束；一串；一群人',
  'BURDEN',
  'n. 负担；重担 v. 使负担',
  'BURGLAR',
  'n. 入室窃贼',
  'BURIAL',
  'n. 埋葬；葬礼',
  'BURN',
  'v. 燃烧；烧伤；晒黑 n. 烧伤',
  'BURST',
  'v. 爆炸；爆裂；突然发生 n. 爆发',
  'BURY',
  'v. 埋葬；掩埋；埋藏',
  'BUSH',
  'n. 灌木；灌木丛',
  'BUSY',
  'a. 忙碌的；热闹的',
  'BUTCHER',
  'n. 屠夫；肉贩 v. 屠宰；残杀',
  'BUTTER',
  'n. 黄油；奶油 v. 涂黄油',
  'BUTTON',
  'n. 纽扣；按钮 v. 扣上纽扣',
  'CABBAGE',
  'n. 卷心菜；洋白菜',
  'CAFÉ',
  'n. 咖啡馆；小餐馆',
  'CAGE',
  'n. 笼子；鸟笼 v. 关进笼子',
  'CAKE',
  'n. 蛋糕；糕点',
  'CALL',
  'v. 叫；称呼；打电话；召集 n. 电话；喊叫',
  'CALM',
  'a. 镇静的；平静的 v. 使平静',
  'CAMEL',
  'n. 骆驼',
  'CAMERA',
  'n. 照相机；摄像机',
  'CAMP',
  'n. 营地；夏令营 v. 露营',
  'CANADA',
  'n. 加拿大',
  'CANAL',
  'n. 运河；水道',
  'CANCEL',
  'v. 取消；废除',
  'CANCER',
  'n. 癌症；肿瘤',
  'CANDLE',
  'n. 蜡烛',
  'CANDY',
  'n. 糖果',
  'CANTEEN',
  'n. 食堂；餐厅；水壶',
  'CAPITAL',
  'n. 首都；资本；大写字母 a. 主要的；死刑的',
  'CAPSULE',
  'n. 胶囊；太空舱',
  'CAPTAIN',
  'n. 船长；队长；上校',
  'CAPTION',
  'n.（图片、漫画等的）说明文字，标题 v. 给…加说明文字',
  'CARBON',
  'n. 碳',
  'CARD',
  'n. 卡片；名片；纸牌；会员卡',
  'CARE',
  'n. 关心；照顾；小心 v. 在意；关心',
  'CAREFUL',
  'a. 小心的，仔细的，谨慎的',
  'CARPET',
  'n. 地毯',
  'CARRIER',
  'n. 搬运者；载体；航空公司；置物架',
  'CARROT',
  'n. 胡萝卜',
  'CARRY',
  'v. 拿；搬；携带；运；传送',
  'CARTOON',
  'n. 动画片；卡通；漫画',
  'CARVE',
  'v. 雕刻；刻',
  'CASE',
  'n. 情况；病例；案件；案例；箱子',
  'CASH',
  'n. 现金，现钞 v. 兑现',
  'CAST',
  'v. 扔；抛；铸造；分配角色 n. 演员阵容',
  'CASTLE',
  'n. 城堡',
  'CASUAL',
  'a. 随意的；偶然的；非正式的',
  'CATCH',
  'v. 接住；捉住；赶上；染上（疾病）',
  'CATER',
  'v. 提供饮食；承办酒席；迎合',
  'CATTLE',
  'n. 牛（总称），家畜',
  'CAUSE',
  'n. 原因；起因；事业 vt. 引起；使发生',
  'CAUTION',
  'n. 谨慎；小心；警告 v. 警告',
  'CAVE',
  'n. 洞穴；地窖 v. 塌陷；屈服',
  'CEILING',
  'n. 天花板；顶棚；上限',
  'CELL',
  'n. 细胞；小牢房；电池；蜂房',
  'CELLAR',
  'n. 地窖；地下储藏室',
  'CENT',
  'n. 美分',
  'CENTRAL',
  'a. 中心的；中央的；主要的',
  'CENTRE',
  'n. 中心；中央',
  'CENTURY',
  'n. 世纪；百年',
  'CERTAIN',
  'a. 确定的；肯定的；某...',
  'CHAIN',
  'n. 链条；连锁店；系列 v. 拴住',
  'CHAIR',
  'n. 椅子；主席职位 v. 主持',
  'CHALK',
  'n. 粉笔 v. 用粉笔写',
  'CHANCE',
  'n. 机会；可能性',
  'CHANGE',
  'n. 变化；零钱 v. 改变；更换；兑换',
  'CHANNEL',
  'n. 频道；通道；海峡；渠道',
  'CHANT',
  'v./ n. 反复呼喊；咏唱；圣歌',
  'CHAOS',
  'n. 混乱，杂乱，紊乱',
  'CHARGE',
  'n. 费用；指控；负责；电荷 v. 收费；充电；指控',
  'CHAPTER',
  'n. 章，章节',
  'CHART',
  'n. 图表；航海图 v. 绘制图表',
  'CHAT',
  'n./ vi. 聊天，闲谈',
  'CHEAP',
  'a. 便宜的；廉价的；低劣的',
  'CHEAT',
  'n./ v. 骗取；作弊；欺骗',
  'CHECK',
  'n. 检查；支票 v. 检查；核对；阻止',
  'CHEEK',
  'n. 面颊，脸蛋',
  'CHEER',
  'n./ vi. 欢呼；喝彩；鼓舞',
  'CHEERS',
  'int. 干杯；(口)谢谢；再见',
  'CHEESE',
  'n. 奶酪',
  'CHEF',
  'n. 厨师长，主厨',
  'CHEMIST',
  'n. 药剂师；化学家',
  'CHEQUE',
  'n. 支票',
  'CHESS',
  'n. 棋；国际象棋',
  'CHEST',
  'n. 胸部；箱子；柜子',
  'CHEW',
  'v. 咀嚼',
  'CHICK',
  'n. 小鸡；少女',
  'CHICKEN',
  'n. 鸡；鸡肉 a. 胆小的',
  'CHIEF',
  'a. 主要的；首要的 n. 首领；头目',
  'CHILD',
  'n. 孩子，儿童',
  'CHIMNEY',
  'n. 烟囱，烟筒',
  'CHINA',
  'n. 中国',
  'CHINESE',
  'a. 中国的；中国人的；中文的 n. 中国人；中文',
  'CHIPS',
  'n. (pl.) 炸土豆条（片）；薯片',
  'CHOICE',
  'n. 选择；抉择 a. 精选的',
  'CHOIR',
  'n. 合唱团，唱诗班',
  'CHOKE',
  'v. 窒息；噎住；阻塞 n. 窒息',
  'CHOOSE',
  'v. 选择；挑选',
  'CHORUS',
  'n. 合唱；合唱曲；副歌 v. 合唱',
  'CHURCH',
  'n. 教堂；教会',
  'CIGAR',
  'n. 雪茄烟',
  'CINEMA',
  'n. 电影院；电影',
  'CIRCLE',
  'n. 圆圈；圈子 v. 画圈；环绕',
  'CIRCUIT',
  'n. 电路；环线；巡回赛',
  'CIRCUS',
  'n. 马戏团；马戏表演',
  'CITIZEN',
  'n. 公民；居民',
  'CITY',
  'n. 城市，都市',
  'CIVIL',
  'a. 国内的；平民的；民用的；文明的',
  'CLAP',
  'v. 拍手；鼓掌 n. 拍手声',
  'CLARIFY',
  'v. 澄清，阐明',
  'CLASS',
  'n. 班级；课；等级；阶级',
  'CLASSIC',
  'a. 经典的；典型的 n. 经典作品',
  'CLAW',
  'n. 爪；钳 v. 用爪抓',
  'CLAY',
  'n. 黏土，陶土',
  'CLEAN',
  'a. 清洁的；干净的 v. 弄干净',
  'CLEANER',
  'n. 清洁工；清洁剂；清洁器',
  'CLEAR',
  'a. 清楚的；清晰的；明亮的 v. 清除；清理',
  'CLEARLY',
  'ad. 清楚地；无疑地',
  'CLERK',
  'n. 职员；办事员；书记员',
  'CLEVER',
  'a. 聪明的，伶俐的',
  'CLICK',
  'v. 点击；发出咔嗒声 n. 咔嗒声',
  'CLIMATE',
  'n. 气候',
  'CLIMB',
  'v. 爬，攀登',
  'CLINIC',
  'n. 诊所',
  'CLOCK',
  'n. 时钟',
  'CLONE',
  'n. 克隆 v. 克隆',
  'CLOSE',
  'v. 关闭 a. 亲密的；近的 ad. 靠近',
  'CLOTH',
  'n. 布；布料',
  'CLOTHES',
  'n. 衣服，衣物',
  'CLOUD',
  'n. 云；阴影',
  'CLOUDY',
  'a. 多云的；阴天的',
  'CLUB',
  'n. 俱乐部；社团；棍棒',
  'CLUMSY',
  'a. 笨拙的，不灵巧的',
  'COACH',
  'n. 教练；长途汽车 v. 训练',
  'COAL',
  'n. 煤',
  'COAST',
  'n. 海岸；海滨',
  'COAT',
  'n. 外套；涂层 v. 涂上',
  'COCK',
  'n. 公鸡',
  'COCOA',
  'n. 可可粉；可可饮料',
  'COFFEE',
  'n. 咖啡',
  'COIN',
  'n. 硬币 v. 创造',
  'COKE',
  'n. 可口可乐',
  'COLD',
  'a. 冷的；冷淡的 n. 感冒；寒冷',
  'COLLAR',
  'n. 衣领；项圈',
  'COLLECT',
  'v. 收集；收藏；收取',
  'COLLEGE',
  'n. 学院；大学',
  'COLOUR',
  'n. 颜色 vt. 给…着色',
  'COMB',
  'n. 梳子 v. 梳；搜寻',
  'COMBINE',
  'v. 结合；联合',
  'COME',
  'v. 来；来到；出现',
  'COMEDY',
  'n. 喜剧',
  'COMFORT',
  'n. 舒适；安慰 v. 安慰',
  'COMMA',
  'n. 逗号',
  'COMMAND',
  'n./ v. 命令；指挥；掌握',
  'COMMENT',
  'n. 评论 v. 发表评论',
  'COMMIT',
  'v. 犯（罪）；委托；承诺',
  'COMMON',
  'a. 普通的；共同的；常见的',
  'COMPANY',
  'n. 公司；陪伴',
  'COMPARE',
  'v. 比较；对照',
  'COMPASS',
  'n. 罗盘，指南针；圆规',
  'COMPETE',
  'v. 比赛，竞赛',
  'COMPLEX',
  'a. 复杂的 n. 建筑群',
  'COMRADE',
  'n. 同志，战友',
  'CONCEPT',
  'n. 概念',
  'CONCERN',
  'v./ n. 涉及；关心；担忧',
  'CONCERT',
  'n. 音乐会；演奏会',
  'CONDEMN',
  'v. 谴责，指责；宣判',
  'CONDUCT',
  'v. 引导；指挥；进行；传导 n. 行为；举止',
  'CONFIRM',
  'v. 证实，证明，确认',
  'CONFUSE',
  'v. 使迷惑，混淆',
  'CONNECT',
  'v. 连接，把…联系起来',
  'CONSIST',
  'v. 包含，组成，构成',
  'CONSULT',
  'v. 咨询，商量',
  'CONSUME',
  'v. 消耗，耗费（燃料、能量、时间等）',
  'CONTAIN',
  'v. 包含；包括；能容纳',
  'CONTENT',
  'a. 甘愿的，满意的 n. 内容；目录',
  'CONTROL',
  'v./n. 控制',
  'CONVEY',
  'v. 表达，传递（思想、感情等）',
  'COOK',
  'n. 厨师 v. 烹调，做饭',
  'COOKER',
  'n. 炊具（锅、炉灶、烤炉等）',
  'COOKIE',
  'n. 小甜饼；饼干',
  'COOL',
  'a. 凉的，凉爽的；冷静的；酷的 v. 使冷却',
  'COPY',
  'n. 抄本，副本；一本（份） v. 抄写；复印；拷贝',
  'CORAL',
  'n. 珊瑚；珊瑚虫',
  'CORN',
  'n. 玉米，谷物',
  'CORNER',
  'n. 角；角落；拐角',
  'CORRECT',
  'v. 改正；纠正 a. 正确的，对的',
  'CORRUPT',
  'a./v. 贪污的，腐败的；使腐化，堕落',
  'COST',
  'v. 值（钱），花费 n. 价格；成本',
  'COSY',
  'a. 暖和舒适的，亲密无间的',
  'COTTAGE',
  'n. (郊外)小屋，村舍，别墅',
  'COTTON',
  'n. 棉花 a. 棉花的',
  'COUGH',
  'n./vi. 咳嗽',
  'COULD',
  'modal v.（can的过去式）可以；可能；能够',
  'COUNT',
  'v. 数，点数；重要；认为',
  'COUNTER',
  'n. 柜台，结账处；计数器',
  'COUNTRY',
  'n. 国家；农村，乡下',
  'COUPLE',
  'n. 夫妇，一对；几个',
  'COURAGE',
  'n. 勇气；胆略',
  'COURSE',
  'n. 过程；课程；路线；一道菜',
  'COURT',
  'n. 法庭；法院；球场；宫廷',
  'COUSIN',
  'n. 堂（表）兄弟，堂（表）姐妹',
  'COVER',
  'n. 盖子；封面；覆盖物 v. 覆盖；遮盖；涉及',
  'COWBOY',
  'n. 牛仔；牧场骑士',
  'CRASH',
  'v./n. 碰撞，撞击；崩溃；坠毁',
  'CRAYON',
  'n. 蜡笔；蜡笔画',
  'CRAZY',
  'a. 疯狂的；狂热的',
  'CREAM',
  'n. 奶油，乳脂；面霜',
  'CREATE',
  'v. 创造；造成',
  'CREDIT',
  'n. 信用；信赖；信誉；学分；赞扬',
  'CRIME',
  'n. 罪，犯罪',
  'CREW',
  'n. 全体船员；全体工作人员',
  'CROP',
  'n. 庄稼；收成；一批',
  'CROSS',
  'v. 越过；穿过 a. 脾气不好的 n. 十字形',
  'CROWD',
  'n. 人群 v. 拥挤，群聚',
  'CROWDED',
  'a. 拥挤的',
  'CRUEL',
  'a. 残忍的，残酷的；无情的',
  'CUBE',
  'n. 立方体；立方',
  'CUBIC',
  'a. 立方体的，立方形的',
  'CUISINE',
  'n. 饭菜，佳肴；烹饪',
  'CULTURE',
  'n. 文化',
  'CURE',
  'n./vt. 治疗；医好；解决',
  'CURIOUS',
  'a. 好奇的；奇异的',
  'CURTAIN',
  'n. 窗帘',
  'CUSHION',
  'n. 垫子；坐垫',
  'CUSTOM',
  'n. 习惯，习俗，风俗',
  'CUSTOMS',
  'n. 海关；关税',
  'CYCLE',
  'vi. 骑自行车 n. 周期，循环',
  'CYCLIST',
  'n. 骑自行车的人',
  'DAILY',
  'a. 每日的；日常的 ad. 每天 n. 日报',
  'DAMAGE',
  'n./vt. 毁坏，损害',
  'DAMP',
  'a./n. 潮湿（的）',
  'DANCE',
  'n./vi. 跳舞',
  'DANGER',
  'n. 危险',
  'DARE',
  'v./aux.（后接不带to的不定式）敢，敢于',
  'DARK',
  'n. 黑暗；暗处；日暮 a. 黑暗的；深色的',
  'DASH',
  'v./n. 快跑，冲刺，短跑',
  'DATA',
  'n. 资料，数据',
  'DATE',
  'n. 日期；约会；枣',
  'DAWN',
  'n. 黎明，拂晓',
  'DEAD',
  'a. 死的；无生命的',
  'DEAF',
  'a. 聋的；不愿听的',
  'DEAL',
  'n. 量，数额；交易 v. 处理；交易',
  'DEAR',
  'int.（表示惊愕）哎呀！a. 亲爱的；贵的',
  'DEATH',
  'n. 死亡',
  'DEBATE',
  'n./v. 讨论，辩论',
  'DEBT',
  'n. 债务；欠款',
  'DECADE',
  'n. 十年期',
  'DECIDE',
  'v. 决定；下决心',
  'DECLARE',
  'v. 声明；断言；宣告',
  'DECLINE',
  'v. 减少，下降，衰退；谢绝',
  'DEED',
  'n. 行为；事迹',
  'DEEP',
  'a. 深的；深厚的 ad. 深',
  'DEEPLY',
  'ad. 深深地',
  'DEER',
  'n. 鹿',
  'DEFEAT',
  'v. 击败；战胜 n. 失败',
  'DEFENCE',
  'n. 防御；防务；辩护',
  'DEFEND',
  'v. 防守；保卫；辩护',
  'DEGREE',
  'n. 程度；度数；学位',
  'DELAY',
  'v./n. 拖延，延误，延迟，延期；耽搁',
  'DELETE',
  'v. 删去',
  'DELIGHT',
  'n. 快乐；乐事 v. 使高兴',
  'DELIVER',
  'v. 投递（信件、邮包等）；发表；接生',
  'DEMAND',
  'v./n. 要求；需求',
  'DENTIST',
  'n. 牙科医生',
  'DEPEND',
  'v. 依靠，依赖，指望；取决于',
  'DEPOSIT',
  'v./n. 订金，押金；放下，放置；储存',
  'DEPTH',
  'n. 深，深度',
  'DESERT',
  'n. 沙漠 v. 舍弃；遗弃',
  'DESERVE',
  'v.（不用于进行时态）应得，应受',
  'DESIGN',
  'n./v. 设计，策划；图案，图样，样式',
  'DESIRE',
  'v./n. 要求；期望；渴望',
  'DESK',
  'n. 书桌，写字台',
  'DESSERT',
  'n. 甜点',
  'DESTROY',
  'v. 破坏，毁坏',
  'DEVELOP',
  'v.（使）发展；（使）发达；（使）发育；开发 vt. 冲洗（照片）',
  'DEVOTE',
  'v. 把…奉献，把…专用（于）',
  'DIAGRAM',
  'n. 图表，图样',
  'DIAL',
  'v. 拨（电话号码）',
  'DIAMOND',
  'n. 钻石，金刚石；方块',
  'DIARY',
  'n. 日记；日记簿',
  'DIET',
  'n. 饮食；日常食物',
  'DIFFER',
  'v. 相异，有区别',
  'DIGEST',
  'v. 消化；领会 n. 摘要',
  'DIGITAL',
  'a. 数字的，数码的',
  'DIGNITY',
  'n. 庄重，庄严，尊严；尊贵，高尚',
  'DILEMMA',
  'n.（进退两难的）窘境，困境',
  'DINE',
  'v. 吃饭；（指正式）进餐',
  'DINNER',
  'n. 正餐，宴会',
  'DIOXIDE',
  'n. 二氧化物',
  'DIPLOMA',
  'n. 毕业文凭；学位证书',
  'DIRECT',
  'a. 直接的；直截了当的 v. 指挥；指导；导演',
  'DIRT',
  'n. 污物；脏物',
  'DIRTY',
  'a. 脏的',
  'DISCUSS',
  'v. 讨论，议论',
  'DISEASE',
  'n. 病，疾病',
  'DISH',
  'n. 盘，碟；盘装菜；盘形物',
  'DISK',
  'n. 磁盘；光盘',
  'DISLIKE',
  'v. 不喜爱；厌恶 n. 厌恶',
  'DISMISS',
  'v. 让……离开；遣散；解散；解雇',
  'DISOBEY',
  'v. 不服从',
  'DISTANT',
  'a. 远的，遥远的',
  'DISTURB',
  'v. 扰乱；打扰',
  'DIVE',
  'v. 跳水；潜水',
  'DIVERSE',
  'a. 不同的，多种多样，形形色色的',
  'DIVIDE',
  'v. 分，划分',
  'DIVORCE',
  'v./n. 离婚',
  'DIZZY',
  'a. 头眩目晕的',
  'DOCTOR',
  'n. 医生，大夫；博士',
  'DOLL',
  'n. 玩偶，玩具娃娃',
  'DOLLAR',
  'n. 元（美国、加拿大、澳大利亚等国货币单位）',
  'DOOR',
  'n. 门',
  'DOUBLE',
  'a. 两倍，双的 n. 两个，双',
  'DOUBT',
  'n./v. 怀疑，疑惑',
  'DOWN',
  'prep. 沿着，沿…而下 ad. 向下',
  'DOZEN',
  'n. 十二个；几十，许多',
  'DRAFT',
  'n./v. 草稿，草案，起草，草拟',
  'DRAG',
  'v. 拖；拽',
  'DRAW',
  'v. 绘画；绘制；拉，拖；提取（金钱）；吸引',
  'DRAWER',
  'n. 抽屉',
  'DRAWING',
  'n. 图画，素描，绘画',
  'DREAM',
  'n. 梦，梦想 v. 做梦；梦想',
  'DRESS',
  'n. 女服，连衣裙；服装 v. 穿衣；穿着',
  'DRIER',
  'n. 烘干机；吹风机',
  'DRILL',
  'n. 钻头；（反复的）训练 vt. 钻孔；重复训练',
  'DRINK',
  'n. 饮料；喝酒 v. 喝，饮',
  'DRIVE',
  'v. 驾驶，开（车）；驱赶；推动 n. 驱动力；驾车',
  'DRIVER',
  'n. 司机，驾驶员',
  'DROP',
  'n. 滴；下降 v. 掉下；落下；投递；放弃',
  'DROWN',
  'v. 溺死；淹没',
  'DRUG',
  'n. 药，药物；毒品',
  'DRUM',
  'n. 鼓 v. 打鼓',
  'DRUNK',
  'a. 醉的 n. 醉汉',
  'DUCK',
  'n. 鸭子 v. 躲避；低下头',
  'DULL',
  'a. 阴暗的；单调无味的；迟钝的',
  'DURING',
  'prep. 在…期间；在…过程中',
  'DUSK',
  'n. 黄昏',
  'DUST',
  'n. 灰尘，尘土 v. 除尘',
  'DUSTBIN',
  'n. 垃圾箱',
  'DUSTY',
  'a. 尘土般的，尘土多的',
  'DUTY',
  'n. 责任，义务；关税',
  'DYNAMIC',
  'a. 充满活力的，精力充沛的；动态的',
  'DYNASTY',
  'n. 王朝，朝代',
  'EACH',
  'a./pron. 每人，每个，每件',
  'EAGER',
  'a. 渴望的，热切的',
  'EAGLE',
  'n. 鹰',
  'EARLY',
  'a. 早的 ad. 早地',
  'EARN',
  'v. 挣得，赚得',
  'EARTH',
  'n. 地球；土，泥；大地',
  'EASE',
  'v. 减轻；缓解（难度或严重程度）n. 轻松',
  'EASILY',
  'ad. 容易地',
  'EAST',
  'n. 东，东方；东部 a. 东方的；东部的 ad. 在东方；向东方',
  'EASTER',
  'n. 复活节',
  'EASTERN',
  'a. 东方的；东部的',
  'EASY',
  'a. 容易的，不费力的',
  'ECOLOGY',
  'n. 生态，生态学',
  'EDGE',
  'n. 边缘；优势 v. 给…加边',
  'EDITION',
  'n.（发行物的）版，版（本）',
  'EDITOR',
  'n. 编辑',
  'EDUCATE',
  'v. 教育，培养',
  'EFFECT',
  'n. 效果；作用 v. 实现，产生',
  'EFFORT',
  'n. 努力，艰难的尝试',
  'EGYPT',
  'n. 埃及',
  'EIGHT',
  'num. 八',
  'EIGHTH',
  'num. 第八',
  'EIGHTY',
  'num. 八十',
  'EITHER',
  'a./pron. 两者之一 conj. 二者之一 ad.（用于否定句）也',
  'ELDER',
  'n. 长者；前辈 a. 年长的',
  'ELECT',
  'v.（投票）选举',
  'ELEGANT',
  'a. 文雅的，漂亮的，精美的',
  'ELEVEN',
  'num. 十一',
  'ELSE',
  'ad. 别的，其他的',
  'EMAIL',
  'n. 电子邮件 v. 发电子邮件',
  'EMBASSY',
  'n. 大使馆',
  'EMPEROR',
  'n. 皇帝',
  'EMPIRE',
  'n. 帝国',
  'EMPLOY',
  'v. 雇佣；使用',
  'EMPTY',
  'a. 空的 v. 倒空',
  'ENDING',
  'n. 结局；结尾，最后',
  'ENDLESS',
  'a. 无止境的；没完的',
  'ENEMY',
  'n. 敌人；敌军',
  'ENERGY',
  'n. 精力，能量',
  'ENGINE',
  'n. 发动机，引擎',
  'ENGLAND',
  'n. 英格兰',
  'ENGLISH',
  'a. 英国的，英国人的，英语的 n. 英语',
  'ENJOY',
  'v. 欣赏；享受乐趣；喜欢',
  'ENLARGE',
  'v. 扩大',
  'ENOUGH',
  'n. 足够；充足 a. 足够；充分的 ad. 足够地；充分地',
  'ENQUIRY',
  'n. 询问',
  'ENTER',
  'v. 进入',
  'ENTIRE',
  'a. 整个的，全部的',
  'ENTRY',
  'n. 进入；入口；登记',
  'ENVY',
  'v./n. 忌妒；羡慕',
  'EQUAL',
  'a. 平等的 v. 等于，使等于',
  'EQUIP',
  'v. 提供设备；装备；配备',
  'ERASER',
  'n. 橡皮擦；黑板擦',
  'ERROR',
  'n. 错误；差错',
  'ERUPT',
  'v.（火山）爆发，喷发',
  'ESCAPE',
  'n./vi. 逃跑；逃脱',
  'ESSAY',
  'n. 散文；文章；随笔',
  'EUROPE',
  'n. 欧洲',
  'EVEN',
  'ad. 甚至，连（…都）；更 a. 平坦的；偶数的',
  'EVENING',
  'n. 傍晚，晚上',
  'EVENT',
  'n. 事件，大事；比赛项目',
  'EVER',
  'ad. 曾经；无论何时',
  'EVERY',
  'a. 每一，每个的',
  'EVIDENT',
  'a. 清楚的，显而易见的',
  'EXACT',
  'adj. 精确的；确切的',
  'EXACTLY',
  'adv. 精确地；确切地；正是',
  'EXAM',
  'n. 考试；测试（examination的缩写）',
  'EXAMINE',
  'v. 检查；诊察；考试',
  'EXAMPLE',
  'n. 例子；榜样',
  'EXCEPT',
  'prep. 除……之外',
  'EXCITE',
  'v. 使兴奋；使激动',
  'EXCUSE',
  'n. 借口；辩解',
  'EXIST',
  'vi. 存在；生存',
  'EXIT',
  'n. 出口；太平门',
  'EXPAND',
  'v. 扩大；增加；扩展',
  'EXPECT',
  'v. 预料；盼望；认为',
  'EXPENSE',
  'n. 消费；支出；费用',
  'EXPERT',
  'n. 专家；能手',
  'EXPLAIN',
  'v. 解释；说明',
  'EXPLODE',
  'v. （使）爆炸；爆发',
  'EXPLOIT',
  'vt. 开采；开发；利用；剥削',
  'EXPLORE',
  'v. 探险；探索；考察',
  'EXPORT',
  'n. 出口；输出',
  'EXPOSE',
  'v. 揭露；暴露',
  'EXPRESS',
  'v. 表达；表示',
  'EXTRA',
  'adj. 额外的；外加的',
  'EXTREME',
  'adj. 极其的；非常的；极端的',
  'FACE',
  'n. 脸；面容',
  'FACIAL',
  'adj. 面部的；面部用的',
  'FACT',
  'n. 事实；现实',
  'FACTORY',
  'n. 工厂',
  'FADE',
  'v. 褪色；消退；逐渐消失',
  'FAIL',
  'v. 失败；不及格；衰退',
  'FAILURE',
  'n. 失败；故障；失败的人',
  'FAIR',
  'adj. 公平的；合理的；白皙的',
  'FAIRLY',
  'adv. 公正地；相当地',
  'FAITH',
  'n. 信仰；信念；信任',
  'FALL',
  'v. (fell, fallen) 落下；降落；倒',
  'FALSE',
  'adj. 错误的；假的；不真实的',
  'FAMILY',
  'n. 家庭；家族；子女',
  'FAMOUS',
  'adj. 著名的',
  'FANCY',
  'adj. 花式的；装饰的；奇特的',
  'FANTASY',
  'n. 幻想；梦想；奇幻作品',
  'FARE',
  'n. （车、船等）费用；票价',
  'FARM',
  'n. 农场；农庄',
  'FARMER',
  'n. 农民',
  'FAST',
  'adj. & adv. 快的；迅速地',
  'FASTEN',
  'v. 扎牢；扣住',
  'FATHER',
  'n. 父亲',
  'FAULT',
  'n. 缺点；毛病；过错',
  'FAVOUR',
  'n. 恩惠；好意；帮助',
  'FEAR',
  'n. 害怕；恐惧；担忧',
  'FEAST',
  'n. 盛宴；宴会；（宗教的）节日',
  'FEATHER',
  'n. 羽毛',
  'FEDERAL',
  'adj. 中央的；联邦的',
  'FEED',
  'v. (fed, fed) 喂（养）；饲（养）',
  'FEEL',
  'v. (felt, felt) 感觉；觉得；摸；触',
  'HERB',
  'n. 草药；香草',
  'HERE',
  'adv. 这里；在这里；向这里',
  'HERO',
  'n. 英雄；勇士；男主角',
  'HEROINE',
  'n. 女英雄；女主角',
  'HERS',
  'pron. 她的',
  'HERSELF',
  'pron. 她自己',
  'HIDE',
  'v. (hid, hidden) 把…藏起来；隐藏',
  'HIGH',
  'adj. 高的；高度的',
  'HIGHWAY',
  'n. 公路；主要交通道路',
  'HILL',
  'n. 小山；丘陵；土堆；斜坡',
  'HILLY',
  'adj. 丘陵的；多小山的',
  'HIMSELF',
  'pron. 他自己',
  'HIRE',
  'vt. 租用',
  'HISTORY',
  'n. 历史；历史学',
  'HIVE',
  'n. 蜂房；蜂箱',
  'HOBBY',
  'n. 业余爱好；嗜好',
  'HOLD',
  'v. (held, held) 拿；抱；握住；举行；进行',
  'HOLE',
  'n. 洞；坑',
  'HOLIDAY',
  'n. 假日；假期',
  'HOLY',
  'adj. 神圣的',
  'HOME',
  'n. 家',
  'HONEST',
  'adj. 诚实的；正直的',
  'HONEY',
  'n. 蜂蜜；亲爱的',
  'HONOUR',
  'n. 荣誉；光荣',
  'HOOK',
  'n. & v. 钩子；衔接；连接',
  'HOORAY',
  'int. 好哇！（欢呼声）',
  'HOPE',
  'n. & v. 希望',
  'HOPEFUL',
  'adj. 有希望的；有前途的',
  'HORSE',
  'n. 马',
  'HOST',
  'n. 主人；节目主持人',
  'HOSTESS',
  'n. 女主人',
  'HOTEL',
  'n. 旅馆；饭店；宾馆',
  'HOUR',
  'n. 小时',
  'HOUSE',
  'n. 房子；住宅',
  'HOWEVER',
  'adv. 可是',
  'HOWL',
  'vi. 嚎叫；嚎哭',
  'HUGE',
  'adj. 巨大的；庞大的',
  'HUMAN',
  'adj. 人的；人类的',
  'HUMOUR',
  'n. 幽默；幽默感（美humor）',
  'HUNDRED',
  'num. 百',
  'HUNGER',
  'n. 饥饿',
  'HUNGRY',
  'adj. （饥）饿的',
  'HUNT',
  'vt. 寻找；狩猎；猎取',
  'HUNTER',
  'n. 猎人',
  'HURRY',
  'vi. 赶快；急忙',
  'HURT',
  'vt. (hurt, hurt) 伤害；受伤；伤人感情',
  'HUSBAND',
  'n. 丈夫',
  'ICELAND',
  'n. 冰岛',
  'IDEA',
  'n. 主意；意见；打算；想法',
  'IDIOM',
  'n. 习语；成语',
  'IGNORE',
  'v. 忽视；对…不理会',
  'ILLEGAL',
  'adj. 非法的',
  'ILLNESS',
  'n. 疾病',
  'IMAGINE',
  'vt. 想像；设想',
  'IMPORT',
  'v. & n. 进口；输入',
  'IMPRESS',
  'vt. 留下极深的印象',
  'IMPROVE',
  'vt. 改进；更新',
  'INCH',
  'n. 英寸',
  'INCLUDE',
  'vt. 包含；包括',
  'INCOME',
  'n. 收入；所得',
  'INDEED',
  'adv. 确实；实在',
  'INDIA',
  'n. 印度',
  'INDIAN',
  'adj. （美洲）印地安人的；印度人的',
  'INFORM',
  'vt. 告诉；通知',
  'INITIAL',
  'adj. 开始的；最初的',
  'INJURE',
  'vt. 损害；伤害',
  'INJURY',
  'n. 受伤处',
  'INLAND',
  'adj. 内陆的；内地的',
  'INSECT',
  'n. 昆虫',
  'INSERT',
  'vt. 插入',
  'INSIDE',
  'prep. 在…里面',
  'INSIST',
  'vi. 坚持；坚决认为',
  'INSPECT',
  'vt. 检查；检验；审视',
  'INSPIRE',
  'vt. 鼓舞；激励',
  'INSTANT',
  'adj. 瞬间；刹那',
  'INSTEAD',
  'adv. 代替；顶替',
  'INSURE',
  'vt. 给……保险',
  'INTEND',
  'vt. 想要；打算',
  'INTO',
  'prep. 到…里；向内；变成',
  'INVENT',
  'vt. 发明；创造',
  'INVITE',
  'vt. 邀请；招待',
  'IRELAND',
  'n. 爱尔兰',
  'IRISH',
  'adj. 爱尔兰的；爱尔兰人的',
  'IRON',
  'n. 铁；熨斗',
  'ISLAND',
  'n. 岛',
  'ITALIAN',
  'adj. 意大利（人）的；意大利语的',
  'ITALY',
  'n. 意大利',
  'ITSELF',
  'pron. 它自己',
  'JACKET',
  'n. 短上衣；夹克衫',
  'JANUARY',
  'n. 一月',
  'JAPAN',
  'n. 日本',
  'JAZZ',
  'n. 爵士音乐；爵士舞曲',
  'JEANS',
  'n. 牛仔裤',
  'JEEP',
  'n. 吉普车',
  'JEWEL',
  'n. 宝石',
  'JEWELRY',
  'n. （总称）珠宝',
  'JOIN',
  'v. 参加；加入；连接；会合',
  'JOKE',
  'n. 笑话',
  'JOURNEY',
  'n. 旅行；路程',
  'JUDGE',
  'n. 裁判；审判员；法官',
  'JUICE',
  'n. 汁、液',
  'JUICY',
  'adj. 多汁的；水分多的',
  'JULY',
  'n. 七月',
  'JUMP',
  'n. 跳跃；跳变',
  'JUNE',
  'n. 六月',
  'JUNGLE',
  'n. 丛林；密林',
  'JUNIOR',
  'adj. 初级的；年少的',
  'JUNK',
  'n. （口语）废品；破烂货',
  'JUST',
  'adv. 刚才；恰好；不过；仅',
  'JUSTICE',
  'n. 正义；公正；司法',
  'KEEP',
  'v. (kept, kept) 保持；保存；继续不断',
  'KEEPER',
  'n. （动物园中的）饲养员；看守人',
  'KETTLE',
  'n. （烧水用的）水壶',
  'KICK',
  'v. & n. 踢',
  'KILL',
  'v. 杀死；弄死',
  'KILO',
  'n. 千克；千米',
  'KIND',
  'n. 种；类',
  'KING',
  'n. 国王',
  'KINGDOM',
  'n. 王国',
  'KISS',
  'n. & vt. 吻；亲吻',
  'KITCHEN',
  'n. 厨房',
  'KITE',
  'n. 风筝',
  'KNEE',
  'n. 膝盖',
  'KNIFE',
  'n. (复 knives) 小刀；匕首；刀片',
  'KNOCK',
  'n. & v. 敲；打；击',
  'KNOW',
  'v. (knew, known) 知道；了解；认识；懂得',
  'LABOUR',
  'n. 劳动（美labor）',
  'LACK',
  'n. & vt. 缺乏；缺少',
  'LADDER',
  'n. 梯子',
  'LADY',
  'n. 女士；夫人',
  'LAKE',
  'n. 湖',
  'LAMB',
  'n. 羔羊',
  'LAME',
  'adj. 跛的；瘸的；残废的',
  'LAMP',
  'n. 灯；油灯；光源',
  'LAND',
  'n. 陆地；土地',
  'LANTERN',
  'n. 灯笼；提灯',
  'LARGE',
  'adj. 大的；巨大的',
  'LASER',
  'n. 激光',
  'LAST',
  'adj. 最近刚过去的；最后的',
  'LATE',
  'adj. 晚的；迟的',
  'LATELY',
  'adv. 最近；不久前',
  'LATER',
  'adv. 晚些的；迟些的',
  'LATEST',
  'adj. 最近的；最新的；最晚的',
  'LATTER',
  'n. （两者之中的）后者',
  'LAUGH',
  'n. & v. 笑；大笑；嘲笑',
  'LAUNDRY',
  'n. 洗衣店；要洗的衣服',
  'LAWYER',
  'n. 律师',
  'LAZY',
  'adj. 懒惰的',
  'LEAD',
  'v. (led, led) 领导；带领',
  'LEADER',
  'n. 领袖；领导人',
  'LEADING',
  'adj. 最主要的；第一位的',
  'LEAF',
  'n. (复 leaves) （树、菜）叶',
  'LEAGUE',
  'n. 联盟；社团',
  'LEAK',
  'vi. 漏；渗',
  'LEARN',
  'vt. (learnt, learnt；-ed -ed) 学；学习；学会',
  'LEARNED',
  'adj. 有才华的；博学的',
  'LEAST',
  'n. 最少；最少量',
  'LEATHER',
  'n. 皮革',
  'LEAVE',
  'v. (left, left) 离开；把…留下；剩下',
  'LECTURE',
  'n. 讲课；演讲',
  'LEFT',
  'adj. 左边的',
  'LEGAL',
  'adj. 与法律有关的；法律的',
  'LEMON',
  'n. 柠檬',
  'LEND',
  'vt. (lent, lent) 借（出）；把…借给',
  'LENGTH',
  'n. 长；长度；段；节',
  'LESS',
  'a. & ad. (little的比较级) 少于；小于',
  'LESSON',
  'n. 课；功课；教训',
  'LETTER',
  'n. 信；字母',
  'LEVEL',
  'n. 水平线；水平',
  'LIBERTY',
  'n. 自由',
  'LIBRARY',
  'n. 图书馆；图书室',
  'LICENSE',
  'n. 执照；许可证',
  'LIFE',
  'n. (复 lives) 生命；生涯；生活；人生；生物',
  'LIFT',
  'v. 举起；抬起；（云、烟等）消散',
  'LIGHT',
  'n. 光；光亮；灯；灯光',
  'LIKE',
  'prep. 像；跟…一样',
  'LIKELY',
  'adj. 很可能的',
  'LIMIT',
  'vt. 限制；减少',
  'LINE',
  'n. 绳索；线；排；行；线路',
  'LINK',
  'v. 连接；联系',
  'LION',
  'n. 狮子',
  'LIQUID',
  'n. & a. 液体；液体的',
  'LIST',
  'n. 一览表；清单',
  'LISTEN',
  'vi. 听；仔细听',
  'LITRE',
  'n. 升；公升（美 liter）',
  'LITTER',
  'v. 乱丢杂物',
  'LITTLE',
  'adj. 小的；少的',
  'LIVE',
  'vi. 生活；居住；活着',
  'LIVELY',
  'adj. 活泼的；充满生气的',
  'LIVING',
  'adj. 活着的',
  'LOAD',
  'n. 担子；货物',
  'LOAF',
  'n. 一个面包',
  'LOCAL',
  'adj. 当地的；地方的',
  'LOCK',
  'n. 锁',
  'LOCUST',
  'n. 蝗虫',
  'LONDON',
  'n. 伦敦',
  'LONELY',
  'adj. 孤独的；寂寞的',
  'LONG',
  'adj. 长的；远的',
  'LOOK',
  'n. 看；瞧',
  'LOOSE',
  'adj. 松散的；宽松的',
  'LORRY',
  'n. （英）运货汽车；卡车',
  'LOSS',
  'n. 丧失；损耗',
  'LOSE',
  'vt. (lost, lost) 失去；丢失',
  'LOST',
  'adj. 丢失的；迷失的',
  'LOUD',
  'adj. 大声的',
  'LOUDLY',
  'adv. 大声地',
  'LOUNGE',
  'n. 休息厅；休息室',
  'LOVE',
  'n. & vt. 爱；热爱；很喜欢',
  'LOVELY',
  'adj. 美好的；可爱的',
  'LUCK',
  'n. 运气；好运',
  'LUCKY',
  'adj. 运气好；侥幸的',
  'LUGGAGE',
  'n. （总称）行李',
  'LUNCH',
  'n. 午餐；午饭',
  'LUNG',
  'n. 肺；肺脏',
  'MACHINE',
  'n. 机器',
  'MADAM',
  'n. 夫人；女士',
  'MAGIC',
  'adj. 有魔力的',
  'MAID',
  'n. 女仆；侍女',
  'MAIL',
  'n. 邮政；邮递',
  'MAILBOX',
  'n. 邮筒；邮箱',
  'MAIN',
  'adj. 主要的',
  'MAJOR',
  'adj. 较大的；主要的',
  'MAKE',
  'vt. (made, made) 制造；做；使得',
  'MALE',
  'adj. 男（性）的；雄的',
  'MANAGE',
  'v. 管理；设法对付',
  'MANAGER',
  'n. 经理',
  'MANKIND',
  'n. 人类；（总称）人',
  'MANNER',
  'n. 方式；态度；举止',
  'MANY',
  'adj. & pron. 许多的；许多人（或物）',
  'MAPLE',
  'n. 枫树',
  'MARBLE',
  'n. 大理石；玻璃弹子',
  'MARCH',
  'n. 游行；行进',
  'MARK',
  'n. 标记',
  'MARKET',
  'n. 市场；集市',
  'MARRIED',
  'adj. 已婚的',
  'MARRY',
  'v. （使）成婚；结婚',
  'MASK',
  'n. 口罩；面罩（具）；遮盖物',
  'MASS',
  'n. 众多；大量；（复）群众',
  'MASTER',
  'vt. 精通；掌握',
  'MATCH',
  'vt. 使相配；使成对',
  'MATTER',
  'n. 要紧事；事情；问题',
  'MATURE',
  'adj. 成熟的',
  'MAXIMUM',
  'a. & n. 最大量（的）；最大限度（的）',
  'MAYBE',
  'adv. 可能；大概；也许',
  'MEAL',
  'n. 一餐（饭）',
  'MEAN',
  'vt. (meant, meant) 意思；意指',
  'MEANING',
  'n. 意思；含意',
  'MEANS',
  'n. 方法；手段；财产',
  'MEASURE',
  'v. 量',
  'MEAT',
  'n. （猪、牛、羊等的）肉',
  'MEDAL',
  'n. 奖牌',
  'MEDIA',
  'n. 大众传播媒介',
  'MEDICAL',
  'adj. 医学的；医疗的',
  'MEDIUM',
  'n. 媒体',
  'MEET',
  'vt. (met, met) 遇见；见到',
  'MEETING',
  'n. 会；集会；会见；汇合点',
  'MELON',
  'n. （甜）瓜；瓜状物',
  'MEMBER',
  'n. 成员；会员',
  'MEMORY',
  'n. 回忆；记忆',
  'MEND',
  'v. 修理；修补',
  'MENTAL',
  'adj. 精神的；脑力的',
  'MENTION',
  'n. 提及；记载',
  'MENU',
  'n. 菜单',
  'MERCY',
  'n. 怜悯',
  'MERELY',
  'adv. 仅仅；只不过',
  'MERRY',
  'adj. 高兴的；愉快的',
  'MESS',
  'n. 凌乱',
  'MESSAGE',
  'n. 消息；音信',
  'MESSY',
  'adj. 乱七八糟的',
  'METAL',
  'n. 金属',
  'METHOD',
  'n. 方法；办法',
  'METRE',
  'n. 米；公尺（美 meter）',
  'MEXICAN',
  'adj. 墨西哥的',
  'MEXICO',
  'n. 墨西哥',
  'MIDDAY',
  'n. 中午；正午',
  'MIDDLE',
  'n. 中间；当中；中级的',
  'MIGHT',
  'modal v. (may的过去式) 可能；也许；或许',
  'MILD',
  'adj. 温和的；暖和的；凉爽的',
  'MILE',
  'n. 英里',
  'MILK',
  'n. 牛奶',
  'MILLION',
  'num. 百万',
  'MIND',
  'n. 思想；想法',
  'MINE',
  'n. 矿藏；矿山',
  'MINERAL',
  'n. 矿物质；矿物',
  'MINIBUS',
  'n. 小型公共汽车',
  'MINIMUM',
  'a. 最小的',
  'MINUS',
  'prep. & a. 负的；减去的',
  'MINUTE',
  'n. 分钟；一会儿；瞬间',
  'MIRROR',
  'n. 镜子',
  'MISS',
  'vt. 失去；错过；缺',
  'MISSILE',
  'n. 导弹',
  'MIST',
  'n. 雾',
  'MISTAKE',
  'n. (mistook, mistaken) 错误',
  'MIXTURE',
  'n. 混合物',
  'MOBILE',
  'adj. 活动的；可移动的',
  'MODEL',
  'n. 模型；原形；范例；模范',
  'MODEM',
  'n. 调制解调器',
  'MODERN',
  'adj. 现代的',
  'MODEST',
  'adj. 谦虚的；谦逊的',
  'MOMENT',
  'n. 片刻；瞬间',
  'MOMMY',
  'n. 妈妈（美，=mummy）',
  'MONDAY',
  'n. 星期一',
  'MONEY',
  'n. 钱；货币',
  'MONITOR',
  'n. （班级内的）班长；纠察生；监视器',
  'MONKEY',
  'n. 猴子',
  'MONTH',
  'n. 月；月份',
  'MOON',
  'n. 月球；月光；月状物',
  'MORAL',
  'adj. 道德的',
  'MORE',
  'a. & ad. 另外的；附加的；较多的',
  'MORNING',
  'n. 早晨；上午',
  'MOSCOW',
  'n. 莫斯科',
  'MOSLEM',
  'n. 伊斯兰教徒；回教徒',
  'MOST',
  'a. & ad. 最多',
  'MOTHER',
  'n. 母亲',
  'MOTOR',
  'n. 发动机；马达',
  'MOTTO',
  'n. 箴言；格言',
  'MOURN',
  'vt. 哀痛；哀悼',
  'MOUSE',
  'n. (复 mice) 鼠；耗子；（计算机）鼠标',
  'MOUTH',
  'n. 嘴；口',
  'MOVE',
  'v. 移动；搬动；搬家',
  'MOVIE',
  'n. （口语）电影',
  'MUCH',
  'adj. 许多的；大量的',
  'MUDDY',
  'adj. 泥泞的',
  'MURDER',
  'vt. 谋杀',
  'MUSEUM',
  'n. 博物馆；博物院',
  'MUSIC',
  'n. 音乐；乐曲',
  'MUSICAL',
  'adj. 音乐的；爱好音乐的',
  'MUST',
  'modal v. 必须；应当；必定是',
  'MUSTARD',
  'n. 芥末；芥子粉',
  'MUTTON',
  'n. 羊肉',
  'MYSELF',
  'pron. 我自己',
  'NAIL',
  'n. 钉；钉子',
  'NAME',
  'n. 名字；姓名；名称',
  'NARROW',
  'adj. 狭窄的',
  'NATION',
  'n. 民族；国家',
  'NATIVE',
  'adj. 本土的；本国的',
  'NATURAL',
  'adj. 自然的',
  'NATURE',
  'n. 自然；性质；种类',
  'NAVY',
  'n. 海军',
  'NEAR',
  'adj. 近的',
  'NEARBY',
  'adj. 附近的',
  'NEARLY',
  'adv. 将近；几乎',
  'NEAT',
  'adj. 整洁的；灵巧的',
  'NECK',
  'n. 颈；脖子',
  'NECKTIE',
  'n. 领带；领花',
  'NEED',
  'n. 需要；需求',
  'NEEDLE',
  'n. 针',
  'NEITHER',
  'pron. （两者）都不；也不',
  'NEPHEW',
  'n. 侄子；外甥',
  'NERVOUS',
  'adj. 紧张不安的',
  'NEST',
  'n. 巢；窝',
  'NETWORK',
  'n. 网络；网状系统',
  'NEVER',
  'adv. 决不；从来没有',
  'NEWS',
  'n. 新闻；消息',
  'NEXT',
  'adj. 最近的；紧挨着的；隔壁的；下一次',
  'NICE',
  'adj. 令人愉快的；好的；漂亮的',
  'NIECE',
  'n. 侄女；甥女',
  'NIGHT',
  'n. 夜；夜间',
  'NINE',
  'num. 九',
  'NINETY',
  'num. 九十',
  'NINTH',
  'num. 第九',
  'NOBLE',
  'adj. 高贵的；贵族的',
  'NOBODY',
  'n. 渺小人物',
  'NOISE',
  'n. 声音；噪声；喧闹声',
  'NOISILY',
  'adv. 喧闹地',
  'NOISY',
  'adj. 喧闹的；嘈杂的',
  'NONE',
  'pron. 无任何东西；无一人',
  'NOODLE',
  'n. 面条',
  'NOON',
  'n. 中午；正午',
  'NORMAL',
  'n. & a. 正常的（状态）',
  'NORTH',
  'adj. 北的；朝北的；从北来的',
  'NOSE',
  'n. 鼻',
  'NOTE',
  'n. 便条；笔记；注释；钞票；音符',
  'NOTHING',
  'n. 没有东西；没有什么',
  'NOTICE',
  'n. 布告；通告；注意',
  'NOVEL',
  'n. （长篇）小说',
  'NOWHERE',
  'adv. 任何地方都不；无处',
  'NUCLEAR',
  'adj. 原子核的；原子能的；核动力的',
  'NUMB',
  'adj. 麻木的；失去知觉的；迟钝的',
  'NUMBER',
  'n. 数；数字；号码；数量',
  'NURSE',
  'n. 护士；保育员',
  'NURSERY',
  'n. 托儿所',
  'NURSING',
  'n. （职业性的）保育；护理',
  'NYLON',
  'n. 尼龙',
  'OBEY',
  'v. 服从；顺从；听从',
  'OBJECT',
  'n. 物；物体；宾语',
  'OBSERVE',
  'v. 观察；监视；观测',
  'OBTAIN',
  'vt. 获得；得到',
  'OBVIOUS',
  'adj. 显然',
  'OCCUR',
  'vi. 发生',
  'OCEAN',
  'n. 海洋',
  'OCEANIA',
  'n. 大洋洲',
  'OCTOBER',
  'n. 十月',
  'OFFENCE',
  'n. 违法行为；犯罪',
  'OFFER',
  'n. & vt. 提供；建议',
  'OFFICE',
  'n. 办公室',
  'OFFICER',
  'n. 军官；公务员；官员；警察；警官',
  'OFTEN',
  'adv. 经常；常常',
  'OLYMPIC',
  'a. & n. 奥林匹克',
  'ONCE',
  'n. & ad. 一次；一度；从前',
  'ONESELF',
  'pron. 自己；自身',
  'ONION',
  'n. 洋葱；洋葱头',
  'ONLY',
  'adj. 惟一的；仅有的',
  'ONTO',
  'prep. 到…的上面',
  'OPEN',
  'adj. 开着的；开的',
  'OPENER',
  'n. 开具；启子',
  'OPENING',
  'n. 开放；口子',
  'OPERA',
  'n. 歌剧',
  'OPERATE',
  'v. 做手术；运转；实施；负责；经营；管理',
  'OPINION',
  'n. 看法；见解',
  'OPPOSE',
  'vt. 反对；反抗',
  'ORAL',
  'adj. 口述的；口头上的',
  'ORANGE',
  'n. 橘子；橙子；橘汁',
  'ORBIT',
  'n. （天体等的）运行轨道',
  'ORDER',
  'n. 顺序',
  'ORGAN',
  'n. （人、动物）器官',
  'ORIGIN',
  'n. 起源；由来',
  'OTHER',
  'pron. 别人；别的东西',
  'OTTAWA',
  'n. 渥太华',
  'OUCH',
  'int. （突然受痛时叫声）哎哟',
  'OUGHT',
  'v. & aux. 应该；应当',
  'OURS',
  'pron. 我们的',
  'OUTCOME',
  'n. 结果；效果',
  'OUTER',
  'adj. 外部的；外面的',
  'OUTING',
  'n. 郊游；远足',
  'OUTLINE',
  'n. 概述；略述',
  'OUTPUT',
  'n. 产量；输出量',
  'OUTSIDE',
  'n. 外面',
  'OUTWARD',
  'adj. 向外的；外出的',
  'OVAL',
  'n. & adj. 椭圆；椭圆形的',
  'OVER',
  'prep. 在…上方；越过；遍及',
  'OWNER',
  'n. 物主；所有人',
  'OXYGEN',
  'n. 氧；氧气',
  'PACE',
  'n. 步子；节奏',
  'PACIFIC',
  'adj. 太平洋的',
  'PACK',
  'n. 包；捆；（猎犬、野兽的）一群',
  'PACKAGE',
  'n. （尤指包装好或密封的容器）一包；一袋；一盒',
  'PACKET',
  'n. 小包裹；袋',
  'PADDLE',
  'n. 桨状物；蹼',
  'PAGE',
  'n. 页；页码',
  'PAIN',
  'n. 疼痛；疼',
  'PAINFUL',
  'adj. 使痛的；使痛苦的',
  'PAINT',
  'n. 油漆',
  'PAINTER',
  'n. 绘画者；（油）画家',
  'PAIR',
  'n. 一双；一对',
  'PALACE',
  'n. 宫；宫殿',
  'PALE',
  'adj. 苍白的；灰白的',
  'PANCAKE',
  'n. 薄煎饼',
  'PANDA',
  'n. 熊猫',
  'PANIC',
  'a. & v. 惊慌；恐慌；惶恐不安',
  'PAPER',
  'n. 纸；报纸',
  'PARCEL',
  'n. 包裹',
  'PARDON',
  'n. 原谅；宽恕；对不起',
  'PARENT',
  'n. 父（母）；双亲',
  'PARIS',
  'n. 巴黎',
  'PARK',
  'n. 公园',
  'PARKING',
  'n. 停车',
  'PARROT',
  'n. 鹦鹉',
  'PART',
  'n. 部分；成分；角色；部件',
  'PARTLY',
  'adv. 部分地；在一定程度上',
  'PARTNER',
  'n. 搭档；合作者',
  'PARTY',
  'n. 聚会；晚会；党派',
  'PASS',
  'vt. 传；递；经过；通过',
  'PASSAGE',
  'n. （文章等的）一节；一段；通道；走廊',
  'PASSIVE',
  'adj. 被动的',
  'PAST',
  'adv. 过',
  'PATENT',
  'n. 专利权；专利证书',
  'PATH',
  'n. 小道；小径',
  'PATIENT',
  'n. 病人',
  'PATTERN',
  'n. 式样',
  'PAUSE',
  'n. & vi. 中止；暂停；停止',
  'PEACE',
  'n. 和平',
  'PEACH',
  'n. 桃子',
  'PEAR',
  'n. 梨子；梨树',
  'PEASANT',
  'n. 农民；佃农',
  'PENCIL',
  'n. 铅笔',
  'PENNY',
  'n. （英）便士；美分',
  'PENSION',
  'n. 养老金',
  'PEOPLE',
  'n. 人；人们；人民',
  'PEPPER',
  'n. 胡椒粉',
  'PERCENT',
  'n. 百分之……',
  'PERFECT',
  'adj. 完美的；极好的',
  'PERFORM',
  'v. 表演；履行；行动',
  'PERFUME',
  'n. 香水',
  'PERHAPS',
  'adv. 可能；或许',
  'PERIOD',
  'n. 时期；时代',
  'PERMIT',
  'vt. 许可；允许',
  'PERSON',
  'n. 人',
  'PEST',
  'n. 害虫',
  'PETROL',
  'n. 石油',
  'PHONE',
  'v. 打电话',
  'PHOTO',
  'n. 照片（=photograph）',
  'PHRASE',
  'n. 短语；习惯用语',
  'PHYSICS',
  'n. 物理（学）',
  'PIANIST',
  'n. 钢琴家',
  'PIANO',
  'n. 钢琴',
  'PICK',
  'v. 拾起；采集；挑选',
  'PICNIC',
  'n. & v. 野餐',
  'PICTURE',
  'n. 图片；画片；照片',
  'PIECE',
  'n. 一块（片、张、件…）',
  'PILE',
  'n. 堆',
  'PILL',
  'n. 药丸；药片',
  'PILLOW',
  'n. 枕头',
  'PILOT',
  'n. 飞行员',
  'PINE',
  'n. 松树',
  'PINK',
  'adj. 粉红色的',
  'PINT',
  'n. （液量单位）品脱',
  'PIONEER',
  'n. 先锋；开拓者',
  'PIPE',
  'n. 管子；输送管',
  'PITY',
  'n. 怜悯；同情',
  'PLACE',
  'n. 地方；处所',
  'PLAIN',
  'adj. 家常的；普通的',
  'PLAN',
  'n. & v. 计划；打算',
  'PLANE',
  'n. 飞机',
  'PLANET',
  'n. 行星',
  'PLANT',
  'vt. 种植；播种',
  'PLASTIC',
  'adj. 塑料的',
  'PLATE',
  'n. 板；片；牌；盘子；盆子',
  'PLAY',
  'v. 玩；打（球）；游戏；播放',
  'PLAYER',
  'n. 比赛者；选手',
  'PLEASE',
  'v. 请；使人高兴；使人满意',
  'PLEASED',
  'adj. 高兴的',
  'PLENTY',
  'n. 充足；大量',
  'PLOT',
  'v. & n. 故事情节；密谋',
  'PLUG',
  'n. 塞子',
  'PLUS',
  'prep. 加；加上',
  'POCKET',
  'n. （衣服的）口袋',
  'POEM',
  'n. 诗',
  'POET',
  'n. 诗人',
  'POINT',
  'v. 指；指向',
  'POISON',
  'n. 毒药',
  'POLE',
  'n. 杆；电线杆',
  'POLICE',
  'n. 警察；警务人员',
  'POLICY',
  'n. 政策；方针；原则',
  'POLISH',
  'v. 擦亮',
  'POLITE',
  'adj. 有礼貌的；有教养的',
  'POLLUTE',
  'vt. 污染',
  'POND',
  'n. 池塘',
  'POOL',
  'n. 水塘；水池',
  'POOR',
  'adj. 贫穷的；可怜的；不好的；差的',
  'POPCORN',
  'n. 爆米花',
  'POPULAR',
  'adj. 流行的；大众的；受欢迎的',
  'PORK',
  'n. 猪肉',
  'PORT',
  'n. 港口；码头',
  'PORTER',
  'n. （火车站或旅馆处的）搬运工',
  'POSSESS',
  'vt. 占有；拥有',
  'POST',
  'n. 邮政；邮寄；邮件',
  'POSTAGE',
  'n. 邮费',
  'POSTBOX',
  'n. 邮箱',
  'POSTER',
  'n. （贴在公共场所的大型）招贴；广告（画）',
  'POSTMAN',
  'n. 邮递员',
  'POTATO',
  'n. 土豆；马铃薯',
  'POUND',
  'n. 磅；英镑',
  'POUR',
  'vi. 倾泻；不断流出',
  'POWDER',
  'n. 粉；粉末',
  'POWER',
  'n. 力；动力；电力',
  'PRAIRIE',
  'n. 大草原',
  'PRAISE',
  'n. & vt. 赞扬；表扬',
  'PRAY',
  'v. 祈祷；祈求',
  'PRAYER',
  'n. 祈祷',
  'PRECISE',
  'adj. 准确的；精确的；确切的',
  'PREDICT',
  'v. 预言；预告；预报',
  'PREFER',
  'vt. 宁愿（选择）；更喜欢',
  'PREMIER',
  'n. 首相；总理',
  'PREPARE',
  'vt. 准备；预备；调制；配制',
  'PRESENT',
  'adj. 出现的；出席的',
  'PRESS',
  'vt. 压；按',
  'PRETEND',
  'vi. 假装；装作',
  'PRETTY',
  'adj. 漂亮的；俊俏的',
  'PREVENT',
  'vt. 防止；预防',
  'PREVIEW',
  'vt. 预习；试演；预展',
  'PRICE',
  'n. 价格；价钱',
  'PRIDE',
  'n. 自豪；骄傲',
  'PRIMARY',
  'adj. 初等的；初级的',
  'PRINT',
  'vt. 印刷',
  'PRINTER',
  'n. 打印机',
  'PRISON',
  'n. 监狱',
  'PRIVATE',
  'adj. 私人的',
  'PRIZE',
  'n. 奖赏；奖品',
  'PROBLEM',
  'n. 问题；难题',
  'PROCESS',
  'n. & v. 过程；加工；处理',
  'PRODUCE',
  'vt. 生产；制造',
  'PRODUCT',
  'n. 产品；制品',
  'PROFIT',
  'n. 利润；收益',
  'PROJECT',
  'n. 工程',
  'PROMISE',
  'n. & vi. 答应；允诺',
  'PROMOTE',
  'v. 促进；推动；促销；晋升',
  'PROPER',
  'adj. 恰当的；合适的',
  'PROTECT',
  'vt. 保护',
  'PROUD',
  'adj. 自豪的；骄傲的',
  'PROVE',
  'vt. 证明',
  'PROVIDE',
  'vt. 提供',
  'PUBLIC',
  'adj. 公共的；公众的',
  'PUBLISH',
  'vt. 出版；发行',
  'PULL',
  'v. 拉；拖',
  'PULSE',
  'n. 脉搏；（光、能量、波等的）脉动；搏动',
  'PUMP',
  'vt. 用泵抽水',
  'PUNISH',
  'v. 惩罚；处罚',
  'PUPIL',
  'n. （小）学生',
  'PURE',
  'adj. 纯的；不掺杂的',
  'PURPLE',
  'n. & a. 紫色（的）',
  'PURPOSE',
  'n. 目的；意图',
  'PURSE',
  'n. 钱包',
  'PUSH',
  'n. & v. 推',
  'PUZZLE',
  'n. 难题；（字、画）谜',
  'PUZZLED',
  'adj. 迷惑的；困惑的',
  'PYRAMID',
  'n. 角锥形；金字塔',
  'QUAKE',
  'n. & v. 震动；颤抖',
  'QUALITY',
  'n. 质量；性质',
  'QUARREL',
  'vi. 争吵；吵架',
  'QUARTER',
  'n. 四分之一；一刻钟',
  'QUEEN',
  'n. 皇后；女王',
  'QUEUE',
  'n. 行列；长队',
  'QUICK',
  'adj. 快的；敏捷的；急剧的',
  'QUIET',
  'adj. 安静的；寂静的',
  'QUILT',
  'n. 被子；被状物',
  'QUIT',
  'v. 离任；离校；戒掉',
  'QUITE',
  'adv. 完全；十分',
  'QUIZ',
  'n. 测验；小型考试',
  'RABBIT',
  'n. 兔；家兔',
  'RACE',
  'n. 种族；民族',
  'RACIAL',
  'adj. 种族的',
  'RADIO',
  'n. 无线电；收音机',
  'RADIUM',
  'n. 镭',
  'RAIL',
  'n. 铁路',
  'RAILWAY',
  'n. 铁路；铁道',
  'RAIN',
  'n. 雨；雨水',
  'RAINBOW',
  'n. 虹；彩虹',
  'RAINY',
  'adj. 下雨的；多雨的',
  'RAISE',
  'vt. 使升高；饲养',
  'RANDOM',
  'adj. 随意的；未经事先考虑的',
  'RANGE',
  'n. & v. 变化；变动；排序',
  'RANK',
  'n. 职衔；军衔',
  'RAPID',
  'adj. 快的；迅速的',
  'RARE',
  'adj. 罕见的；稀有的',
  'RATE',
  'n. & v. 率；评估；评价',
  'RATHER',
  'adv. 相当；宁可',
  'RAZOR',
  'n. 剃须刀',
  'REACH',
  'v. 到达；伸手（脚）够到',
  'REACT',
  'v. 回应；过敏；起物理、化学反应',
  'READ',
  'v. (read, read) 读；朗读',
  'READING',
  'n. 阅读；朗读',
  'READY',
  'adj. 准备好的',
  'REAL',
  'adj. 真实的；确实的',
  'REALITY',
  'n. 现实',
  'REALISE',
  'vt. 认识到；实现（美 realize）',
  'REALLY',
  'adv. 真正地；到底；确实',
  'REASON',
  'vi. 评理；劝说',
  'REBUILD',
  'vt. (rebuilt, rebuilt) 重建',
  'RECEIPT',
  'n. 收据',
  'RECEIVE',
  'v. 收到；得到',
  'RECENT',
  'adj. 近来的；最近的',
  'RECIPE',
  'n. 烹饪法；食谱',
  'RECITE',
  'v. 背诵',
  'RECORD',
  'n. 记录；唱片',
  'RECOVER',
  'vi. 痊愈；恢复',
  'RECYCLE',
  'vt. 回收；再循环',
  'REDUCE',
  'vt. 减少；缩减',
  'REFER',
  'vi. 谈到；提到；涉及；有关',
  'REFEREE',
  'n. 裁判；仲裁；调解员',
  'REFLECT',
  'v. 反映；反射',
  'REFORM',
  'v. & n. 改革；改进；改良',
  'REFRESH',
  'v. 使恢复精力；提醒',
  'REFUSAL',
  'n. 拒绝',
  'REFUSE',
  'vi. 拒绝；不愿',
  'REGARD',
  'v. 把……看作',
  'REGARDS',
  'n. 问候；致意',
  'REGRET',
  'n. & vt. 可惜；遗憾；痛惜；哀悼',
  'REGULAR',
  'adj. 规则的；经常的',
  'REJECT',
  'v. 拒绝',
  'RELATE',
  'vi. 有关；涉及',
  'RELAX',
  'v. （使）放松；轻松',
  'RELAY',
  'n. 接力；接替人；中转',
  'RELIEF',
  'n. 轻松；解脱；缓和；救济',
  'RELY',
  'v. 依赖；依靠',
  'REMAIN',
  'vt. 余下；留下',
  'REMARK',
  'n. 陈述；话；议论',
  'REMIND',
  'vt. 提醒；使记起',
  'REMOTE',
  'adj. 偏远的；偏僻的',
  'REMOVE',
  'vt. 移动；拿走；脱掉（衣服等）',
  'RENT',
  'n. & v. 租金',
  'REPAIR',
  'n. & vt. 修理；修补',
  'REPAIRS',
  'n. 修理工作',
  'REPEAT',
  'vt. 重说；重做',
  'REPLACE',
  'vt. 取代',
  'REPLY',
  'n. 回答；答复',
  'REPORT',
  'n. & v. 报道；报告',
  'REQUEST',
  'n. 请求；要求的事物',
  'REQUIRE',
  'vt. 需求；要求',
  'RESCUE',
  'vt. 营救；援救',
  'RESERVE',
  'n. & v. 储备；预定',
  'RESIGN',
  'v. 辞职',
  'RESIST',
  'v. 抵抗；挡开',
  'RESPECT',
  'vt. & n. 尊敬；尊重',
  'RESPOND',
  'v. 回答；回应；作出反应',
  'REST',
  'n. 休息；剩余的部分；其余的人（物）',
  'RESULT',
  'n. 结果；效果',
  'RETELL',
  'vt. (retold, retold) 重讲；重复；复述',
  'RETIRE',
  'v. 退休',
  'RETURN',
  'v. 归还',
  'REUSE',
  'vt. 重新使用；循环使用',
  'REVIEW',
  'vt. 重新调查；回顾；复习',
  'REWARD',
  'n. 奖赏',
  'REWIND',
  'v. 回转（磁带等）',
  'REWRITE',
  'vt. (rewrote, rewritten) 重写',
  'RHYME',
  'n. & v. 押韵',
  'RICE',
  'n. 稻米；米饭',
  'RICH',
  'adj. 富裕的；有钱的',
  'RIDDLE',
  'n. 谜（语）',
  'RIDE',
  'v. (rode, ridden) 骑（马、自行车）；乘车',
  'RIGHT',
  'n. 权利',
  'RING',
  'v. (rang, rung) （钟、铃等）响；打电话',
  'RIGID',
  'adj. 死板的；僵硬的；固执的',
  'RIPE',
  'adj. 成熟的；熟的',
  'RIPEN',
  'v. 成熟',
  'RISE',
  'vi. (rose, risen) 上升；上涨',
  'RISK',
  'n. & v. 危险；风险；冒险',
  'RIVER',
  'n. 江；河；水道；巨流',
  'ROAD',
  'n. 路；道路',
  'ROAST',
  'v. 烤（肉）',
  'ROBOT',
  'n. 机器人',
  'ROCK',
  'n. 岩石；大石头',
  'ROCKET',
  'n. 火箭',
  'ROLE',
  'n. 角色',
  'ROLL',
  'v. 滚动；打滚',
  'ROLLER',
  'n. 滚筒；辊',
  'ROOF',
  'n. 屋顶；顶部',
  'ROOM',
  'n. 房间；室；空间；地方',
  'ROOSTER',
  'n. （美）公鸡',
  'ROOT',
  'n. 根；根源；起源',
  'ROPE',
  'n. 绳；索',
  'ROSE',
  'n. 玫瑰花',
  'ROUGH',
  'adj. 粗糙的；粗略的',
  'ROUND',
  'adv. 转过来',
  'ROUTINE',
  'n. 常规；正常顺序；无聊',
  'ROYAL',
  'adj. 皇家的；王室的；国王的；女王的',
  'RUBBER',
  'n. 橡胶；合成橡胶',
  'RUBBISH',
  'n. 垃圾；废物',
  'RUDE',
  'adj. 无理的；粗鲁的',
  'RUGBY',
  'n. （英）橄榄球',
  'RUIN',
  'vt. （使）毁坏；（使）毁灭',
  'RULE',
  'n. 规则；规定',
  'RULER',
  'n. 统治者；直尺',
  'RUNNER',
  'n. 赛跑者；操作者；滑行装置',
  'RUNNING',
  'n. 跑步',
  'RUSH',
  'vi. 冲；奔跑',
  'RUSSIA',
  'n. 俄罗斯；俄国',
  'RUSSIAN',
  'adj. 俄国人的；俄语的',
  'SACRED',
  'adj. 神圣的',
  'SADNESS',
  'n. 悲哀；忧伤',
  'SAFE',
  'adj. 安全的',
  'SAFETY',
  'n. 安全；保险',
  'SAIL',
  'n. 航行',
  'SAILING',
  'n. 航海',
  'SAILOR',
  'n. 水手；海员',
  'SALAD',
  'n. 色拉（西餐中的一种菜）',
  'SALARY',
  'n. 薪金；薪水',
  'SALE',
  'n. 卖；出售',
  'SALT',
  'n. 盐',
  'SALTY',
  'adj. 盐的；咸的；含盐的',
  'SALUTE',
  'v. & n. 敬礼',
  'SAME',
  'n. 同样的事',
  'SAND',
  'n. 沙；沙子',
  'SATISFY',
  'vt. 满足；使满意',
  'SAUCE',
  'n. 酱汁；调味汁',
  'SAUCER',
  'n. 茶碟；茶托；小圆盘',
  'SAUSAGE',
  'n. 香肠；腊肠',
  'SAVAGE',
  'n. 野蛮人；未开化的人',
  'SAVE',
  'vt. 救；挽救；节省',
  'SAYING',
  'n. 说；俗话；谚语',
  'SCAN',
  'v. 略读；浏览；扫描',
  'SCAR',
  'n. 伤疤；伤痕',
  'SCARE',
  'v. 使害怕；使恐惧',
  'SCARF',
  'n. 领巾；围巾',
  'SCENE',
  'n. （戏剧、电影等的）一场；场景；布景',
  'SCENERY',
  'n. 风景；景色；风光',
  'SCHOOL',
  'n. 学校',
  'SCHOLAR',
  'n. 学者',
  'SCIENCE',
  'n. 科学；自然科学',
  'SCOLD',
  'vt. 责骂',
  'SCORE',
  'n. & v. 得分；分数',
  'SCORES',
  'n. 许多；很多',
  'SCRATCH',
  'v. & n. 划破；划痕；划伤',
  'SCREAM',
  'n. 尖叫',
  'SCREEN',
  'n. 幕；荧光屏',
  'SEAGULL',
  'n. 海鸥',
  'SEAL',
  'n. 海豹',
  'SEAMAN',
  'n. 水手；海员',
  'SEARCH',
  'n. & v. 搜寻；搜查',
  'SEASIDE',
  'n. 海滨',
  'SEASON',
  'n. 季；季节',
  'SEAT',
  'n. 座位；座',
  'SEAWEED',
  'n. 海草；海藻；海带',
  'SECOND',
  'n. 秒',
  'SECRET',
  'n. 秘密；内情',
  'SECTION',
  'n. 段；部分；部门',
  'SECURE',
  'adj. 安心的；有把握的；牢靠的',
  'SEED',
  'n. 种子',
  'SEEK',
  'vt. (sought, sought) 试图；探寻',
  'SEEM',
  'v. 似乎；好像',
  'SEIZE',
  'vt. 抓住（时机等）',
  'SELDOM',
  'adv. 很少；不常',
  'SELECT',
  'vt. 选择；挑选；选拔',
  'SELF',
  'n. 自己；自我；自身',
  'SELFISH',
  'adj. 自私的',
  'SELL',
  'v. (sold, sold) 卖；售',
  'SEND',
  'v. (sent, sent) 打发；派遣；送；邮寄',
  'SENIOR',
  'adj. 年长的；资深的；高年级的',
  'SENSE',
  'n. 感觉；意识',
  'SERIOUS',
  'adj. 严肃的；严重的；认真的',
  'SERVANT',
  'n. 仆人；佣人',
  'SERVE',
  'vt. 招待（顾客等）；服务',
  'SERVICE',
  'n. 服务',
  'SESSION',
  'n. 一场；一节；一段时间',
  'SETTLE',
  'vi. 安家；定居',
  'SETTLER',
  'n. 移居者；开拓者',
  'SEVEN',
  'num. 七',
  'SEVENTH',
  'num. 第七',
  'SEVENTY',
  'num. 七十',
  'SEVERAL',
  'pron. 几个；数个',
  'SEVERE',
  'adj. 极为恶劣的；十分严重的',
  'SHABBY',
  'adj. 破旧的；破烂的；衣衫褴褛的',
  'SHADE',
  'n. 阴凉处；树荫处',
  'SHADOW',
  'n. 影子；阴影',
  'SHAKE',
  'v. (shook, shaken) （使）动摇；震动',
  'SHALL',
  'v. aux. （表示将来）将要；会；…好吗',
  'SHALLOW',
  'adj. 浅的；不深的；肤浅的',
  'SHAME',
  'n. 遗憾的事；羞愧',
  'SHAPE',
  'n. 形状；外形',
  'SHARE',
  'vt. 分享；共同使用',
  'SHARK',
  'n. 鲨鱼',
  'SHARP',
  'adj. 锋利的；尖的',
  'SHARPEN',
  'v. （使）变锐利；削尖',
  'SHAVE',
  'v. (shaved, shaved 或 shaven) 刮（脸、胡子）',
  'SHAVER',
  'n. 电动剃须刀',
  'SHEEP',
  'n. (复 sheep) （绵）羊；羊皮；驯服者',
  'SHEET',
  'n. 成幅的薄片；薄板',
  'SHELF',
  'n. (复 shelves) 架子；搁板；格层；礁；陆架',
  'SHELTER',
  'n. 掩蔽；隐蔽处',
  'SHINE',
  'n. 光泽；光彩；阳光；晴天',
  'SHIP',
  'n. 船；轮船',
  'SHIRT',
  'n. 男衬衫',
  'SHOCK',
  'vt. 使震惊',
  'SHOE',
  'n. 鞋',
  'SHOOT',
  'v. (shot, shot) 射击；射中；发射',
  'SHOP',
  'vi. 买东西',
  'SHORE',
  'n. 滨；岸',
  'SHORT',
  'adj. 短的；矮的',
  'SHORTLY',
  'adv. 不久',
  'SHORTS',
  'n. 短裤；运动短裤',
  'SHOT',
  'n. 射击；开枪；开炮；射击声；子弹',
  'SHOULD',
  'v. mod. 应当；应该；会',
  'SHOUT',
  'n. & v. 喊；高声呼喊',
  'SHOW',
  'n. 展示；展览（会）；演出',
  'SHOWER',
  'n. 阵雨；淋浴',
  'SHRINK',
  'v. (shrank, shrunk / shrunk, shrunken) 缩小；收缩；减少',
  'SHUT',
  'v. (shut, shut) 关上；封闭；禁闭',
  'SHUTTLE',
  'n. （往返于两个定点之间的）班车/机',
  'SICK',
  'adj. 有病的；患病的；（想）呕吐',
  'SIDE',
  'n. 边；旁边；面；侧面',
  'SIGH',
  'vi. 叹息；叹气',
  'SIGHT',
  'n. 情景；风景；视力',
  'SIGN',
  'n. 符号；标记',
  'SIGNAL',
  'n. 信号；暗号',
  'SILENCE',
  'n. 安静；沉默',
  'SILENT',
  'adj. 无声的；无对话的',
  'SILK',
  'n. （蚕）丝；丝织品',
  'SILLY',
  'adj. 傻的；愚蠢的',
  'SILVER',
  'n. 银',
  'SIMILAR',
  'adj. 相似的；像',
  'SIMPLE',
  'adj. 简单的；简易的',
  'SIMPLY',
  'adv. 简单地；（加强语气）的确',
  'SINCE',
  'adv. 从那时以来',
  'SING',
  'v. (sang, sung) 唱；唱歌',
  'SINGER',
  'n. 歌唱家；歌手',
  'SINGLE',
  'adj. 单一的；单个的',
  'SINK',
  'n. 洗涤槽；污水槽',
  'SISTER',
  'n. 姐；妹',
  'SIXTH',
  'num. 第六',
  'SIXTY',
  'num. 六十',
  'SIXTEEN',
  'num. 十六',
  'SIZE',
  'n. 尺寸；大小',
  'SKATE',
  'vi. 溜冰；滑冰',
  'SKILL',
  'n. 技能；技巧',
  'SKILLED',
  'adj. 熟练的；有技能的',
  'SKIN',
  'n. 皮；皮肤；兽皮',
  'SKIP',
  'v. 蹦蹦跳跳；跳绳',
  'SKIRT',
  'n. 女裙',
  'SLAVE',
  'n. 奴隶',
  'SLAVERY',
  'n. 奴隶制度',
  'SLEEP',
  'n. 睡觉',
  'SLEEPY',
  'adj. 想睡的；困倦的；瞌睡的',
  'SLEEVE',
  'n. 袖子；袖套',
  'SLICE',
  'n. 片；切面（薄）片',
  'SLIDE',
  'n. 幻灯片；滑道',
  'SLIGHT',
  'adj. 轻微的；细小的',
  'SLIM',
  'adj. 苗条的；纤细的',
  'SLIP',
  'n. 片；条；纸片；纸条',
  'SLOW',
  'adv. 慢慢地；缓慢地',
  'SMALL',
  'adj. 小的；少的',
  'SMART',
  'adj. 灵巧的；伶俐的；（人、服装等）时髦的；帅的',
  'SMELL',
  'v. (smelt, smelt 或 -ed, -ed) 嗅；闻到；发气味',
  'SMELLY',
  'adj. 有臭味的；发出臭味的',
  'SMILE',
  'n. & v. 微笑',
  'SMOG',
  'n. 烟雾（= smoke + fog）',
  'SMOKE',
  'n. 烟',
  'SMOKER',
  'n. 吸烟者',
  'SMOKING',
  'n. 吸烟；抽烟；冒烟',
  'SMOOTH',
  'adj. 光滑的；平坦的',
  'SNACK',
  'n. 小吃',
  'SNAKE',
  'n. 蛇',
  'SNATCH',
  'v. 夺；夺得；夺走',
  'SNEAKER',
  'n. （复）轻便运动鞋（美）',
  'SNEEZE',
  'v. 打喷嚏',
  'SNIFF',
  'v. 抽鼻子（哭、患感冒时）',
  'SNOW',
  'n. 雪',
  'SNOWMAN',
  'n. 雪人',
  'SNOWY',
  'adj. 雪（白）的；下雪的；多（积）雪的',
  'SOAP',
  'n. 肥皂',
  'SOCCER',
  'n. 英式足球',
  'SOCIAL',
  'adj. 社会的；社交的',
  'SOCIETY',
  'n. 社会',
  'SOCK',
  'n. 短袜',
  'SOCKET',
  'n. （电源）插座',
  'SOFA',
  'n. （长）沙发',
  'SOFT',
  'adj. 软的；柔和的',
  'SOIL',
  'n. 土壤；土地',
  'SOLAR',
  'adj. 太阳的',
  'SOLDIER',
  'n. 士兵；战士',
  'SOLID',
  'adj. 结实的；固体的',
  'SOME',
  'adj. 一些；若干；有些；某一',
  'SOMEONE',
  'pron. 某一个人',
  'SONG',
  'n. 歌唱；歌曲',
  'SOON',
  'adv. 不久；很快；一会儿',
  'SORROW',
  'n. 悲伤；悲痛',
  'SORRY',
  'adj. 对不起；抱歉；难过的',
  'SORT',
  'vt. 把…分类；拣选',
  'SOUL',
  'n. 灵魂；心灵；气魄',
  'SOUND',
  'vi. 听起来；发出声音',
  'SOUP',
  'n. 汤',
  'SOUR',
  'adj. 酸的；馊的',
  'SOUTH',
  'adj. 南（方）的；向南的；从南来的',
  'SPACE',
  'n. 空间',
  'SPADE',
  'n. 铲子；纸牌中的黑桃',
  'SPAIN',
  'n. 西班牙',
  'SPANISH',
  'adj. 西班牙人的；西班牙的；西班牙语的',
  'SPARE',
  'adj. 空闲的；多余的；剩余的',
  'SPARROW',
  'n. 麻雀；雀型鸟类',
  'SPEAK',
  'v. (spoke, spoken) 说；讲；谈话；发言',
  'SPEAKER',
  'n. 演讲人；演说家',
  'SPEAR',
  'n. 矛；枪；梭镖',
  'SPECIAL',
  'adj. 特别的；专门的',
  'SPEECH',
  'n. 演讲',
  'SPEED',
  'n. 速度',
  'SPELL',
  'vt. 拼写',
  'SPEND',
  'v. (spent, spent) 度过；花费（钱、时间等）',
  'SPIN',
  'v. & n. 纺；（使）快速旋转；旋转运动',
  'SPIRIT',
  'n. 精神',
  'SPIT',
  'v. 吐唾沫；吐痰',
  'SPLIT',
  'v. 撕开；切开',
  'SPOKEN',
  'adj. 口语的',
  'SPONSOR',
  'n. 赞助者；赞助商',
  'SPOON',
  'n. 匙；调羹',
  'SPORT',
  'n. 体育运动；锻炼；(复，英)运动会',
  'SPOT',
  'n. 斑点；污点；场所；地点',
  'SPRAY',
  'n. & v. 水雾；喷雾（器）；喷洒',
  'SPREAD',
  'v. 延伸；展开',
  'SPRING',
  'n. 春天；春季',
  'SQUARE',
  'n. 广场',
  'SQUEEZE',
  'n. 挤压；捏；塞',
  'SQUID',
  'n. 鱿鱼',
  'STABLE',
  'adj. 稳固的；牢固的',
  'STADIUM',
  'n. （露天）体育场',
  'STAFF',
  'n. 全体职工（雇员）',
  'STAGE',
  'n. 舞台；阶段',
  'STAIN',
  'n. 污点；污渍；染色剂',
  'STAIR',
  'n. 楼梯',
  'STAMP',
  'n. 邮票',
  'STAND',
  'n. 站；立；停止；立场；地位；台；坛；摊',
  'STAR',
  'n. 星；恒星',
  'STARE',
  'vi. 盯；凝视',
  'START',
  'v. 开始；着手；出发',
  'STARVE',
  'v. 饿死',
  'STATE',
  'n. 状态；情形；国家；（美国的）州',
  'STATION',
  'n. 站；所；车站；电台',
  'STATUE',
  'n. 雕像；塑像',
  'STATUS',
  'n. 法律地位（身份）',
  'STAY',
  'n. & vi. 停留；逗留；呆',
  'STEADY',
  'adj. 稳固的；平稳的',
  'STEAK',
  'n. 牛排；肉排；鱼排',
  'STEAL',
  'vt. (stole, stolen) 偷；窃取',
  'STEAM',
  'n. 汽；水蒸气',
  'STEEL',
  'n. 钢；钢铁',
  'STEEP',
  'adj. 险峻的；陡峭的',
  'STEP',
  'n. 脚步；台阶；梯级',
  'STEWARD',
  'n. （火车、飞机、轮船等）男服务员；男乘务员',
  'STICK',
  'v. (stuck, stuck) 粘住；钉住；坚持',
  'STILL',
  'adj. 不动的；平静的',
  'STOMACH',
  'n. 胃；胃部',
  'STONE',
  'n. 石头；石料',
  'STOP',
  'n. 停；（停车）站',
  'STORAGE',
  'n. 贮藏；储存',
  'STORE',
  'n. 商店',
  'STORM',
  'n. 风暴；暴（风）雨',
  'STORY',
  'n. 故事；小说',
  'STOUT',
  'adj. 肥壮的；厚实牢固的',
  'STOVE',
  'n. （供烹饪用的）火炉；煤炉；电炉',
  'STRAIT',
  'n. 海峡',
  'STRANGE',
  'adj. 奇怪的；奇特的；陌生的',
  'STRAW',
  'n. 稻草',
  'STREAM',
  'n. 小河；溪流',
  'STREET',
  'n. 街；街道',
  'STRESS',
  'n. 精神压力；心理负担',
  'STRICT',
  'adj. 严格的；严密的',
  'STRIKE',
  'v. (struck, struck 或 stricken) 擦（打）火；侵袭；（钟）鸣；敲（响）；罢工',
  'STRING',
  'n. 细绳；线；带',
  'STRONG',
  'adj. 强（壮）的；坚固的；强烈的；坚强的',
  'STUDENT',
  'n. 学生',
  'STUDIO',
  'n. 工作室；演播室',
  'STUDY',
  'v. 学习；研究',
  'STUPID',
  'adj. 愚蠢的；笨的',
  'STYLE',
  'n. 方式；作风；款式',
  'SUBJECT',
  'n. 题目；主题；学科；主语；主体',
  'SUBMIT',
  'v. 提交；呈递（文件、建议等）',
  'SUCCEED',
  'vi. 成功',
  'SUCCESS',
  'n. 成功',
  'SUCH',
  'adv. 那么',
  'SUCK',
  'vt. 吸吮',
  'SUDDEN',
  'adj. 突然的',
  'SUFFER',
  'vi. 受苦；遭受',
  'SUGAR',
  'n. 糖',
  'SUGGEST',
  'vt. 建议；提议',
  'SUIT',
  'vt. 适合',
  'SUITE',
  'n. 套间；组曲',
  'SUMMARY',
  'n. 摘要；概要',
  'SUMMER',
  'n. 夏天；夏季',
  'SUNDAY',
  'n. 星期日',
  'SUNNY',
  'adj. 晴朗的；阳光充足的',
  'SUNRISE',
  'n. 黎明；拂晓',
  'SUNSET',
  'n. 日落（时分）',
  'SUPER',
  'adj. 顶好的；超级的',
  'SUPERB',
  'adj. 卓越的；质量极高的',
  'SUPPER',
  'n. 晚餐；晚饭',
  'SUPPLY',
  'vt. & n. 供给；供应',
  'SUPPORT',
  'vt. & n. 支持；赞助',
  'SUPPOSE',
  'vt. 猜想；假定；料想',
  'SUPREME',
  'adj. 至高无上的；最高的',
  'SURE',
  'adj. 确信；肯定',
  'SURFACE',
  'n. 表面',
  'SURGEON',
  'n. 外科医生',
  'SURPLUS',
  'n. 过剩；剩余',
  'SURVIVE',
  'v. 生存；存活；幸免于难',
  'SUSPECT',
  'n. 犯罪嫌疑人',
  'SWALLOW',
  'vt. 吞下；咽下',
  'SWAP',
  'v. 交换（东西）',
  'SWEAR',
  'v. (swore, sworn) 咒骂；诅咒',
  'SWEAT',
  'n. 汗；汗水',
  'SWEATER',
  'n. 厚运动衫；毛衣',
  'SWEEP',
  'v. (swept, swept) 扫除；扫',
  'SWEET',
  'n. 甜食；蜜饯；甜点；糖果；芳香',
  'SWELL',
  'v. (swelled, swollen) 肿胀',
  'SWIFT',
  'adj. 快的；迅速的',
  'SWIM',
  'n. 游泳',
  'SWING',
  'vt. 挥舞；摆动',
  'SWISS',
  'adj. 瑞士人的',
  'SWITCH',
  'v. & n. 开关；转换；改变',
  'SWORD',
  'n. 剑；刀',
  'SYMBOL',
  'n. 象征',
  'SYMPTOM',
  'n. 症状',
  'SYSTEM',
  'n. 体系；系统',
  'TABLE',
  'n. 桌子；表格',
  'TABLET',
  'n. 药片',
  'TAIL',
  'n. （动物的）尾巴',
  'TAILOR',
  'n. 裁缝',
  'TAKE',
  'vt. (took, taken) 拿；拿走；做；服用；乘坐；花费',
  'TALE',
  'n. 故事；传说',
  'TALENT',
  'n. 天才；天赋',
  'TALK',
  'n. & v. 谈话；讲话；演讲；交谈',
  'TALL',
  'adj. 高的',
  'TANK',
  'n. 储水容量；坦克',
  'TANKER',
  'n. 油船',
  'TAPE',
  'n. 磁带；录音带',
  'TARGET',
  'n. & v. 目标；把…作为攻击目标',
  'TASK',
  'n. 任务；工作',
  'TASTE',
  'n. 品尝；尝味；味道',
  'TASTY',
  'adj. 味道好的',
  'TAXI',
  'n. 出租汽车',
  'TEACH',
  'v. (taught, taught) 教书；教',
  'TEACHER',
  'n. 教师；教员',
  'TEAM',
  'n. 队；组',
  'TEAPOT',
  'n. 茶壶',
  'TEAR',
  'n. 眼泪',
  'TEASE',
  'v. 取笑；戏弄；寻开心',
  'TELL',
  'vt. (told, told) 告诉；讲述；吩咐',
  'TEMPLE',
  'n. 庙宇；寺院',
  'TEND',
  'v. 往往会；常常就；倾向；趋于',
  'TENNIS',
  'n. 网球',
  'TENSE',
  'adj. 心烦意乱的；紧张的',
  'TENSION',
  'n. 紧张局势；矛盾',
  'TENT',
  'n. 帐篷',
  'TERM',
  'n. 学期；术语；条款；项',
  'TERRIFY',
  'vt. 使人感到恐怖',
  'TERROR',
  'n. 恐惧；惊恐',
  'TEST',
  'vt. & n. 测试；考查；试验',
  'TEXT',
  'n. 文本；课文',
  'THAN',
  'conj. 比',
  'THANK',
  'vt. 感谢；致谢；道谢',
  'THAT',
  'adj. & pron. 那；那个',
  'THEATRE',
  'n. 剧场；戏院（美 theater）',
  'THEFT',
  'n. 盗窃案',
  'THEIR',
  'pron. 他（她、它）们的',
  'THEIRS',
  'pron. 他（她、它）们的',
  'THEM',
  'pron. 他/她/它们（宾格）',
  'THEME',
  'n. 主题',
  'THEN',
  'adv. 当时；那时；然后；那么',
  'THEORY',
  'n. 理论',
  'THERE',
  'int. 那！你瞧（表示引起注意）',
  'THERMOS',
  'n. 热水瓶',
  'THESE',
  'adj. & pron. 这些',
  'THEY',
  'pron. 他（她）们；它们',
  'THICK',
  'adj. 厚的',
  'THIEF',
  'n. (复 thieves) 窃贼；小偷',
  'THIN',
  'adj. 薄的；瘦的；稀的',
  'THING',
  'n. 东西；(复)物品；用品；事情；事件',
  'THINK',
  'v. (thought, thought) 想；认为；考虑',
  'THIRD',
  'num. 第三',
  'THIRST',
  'n. 渴；口渴',
  'THIRSTY',
  'adj. 渴的',
  'THIRTY',
  'num. 三十',
  'THIS',
  'adj. & pron. 这；这个',
  'THOSE',
  'adj. & pron. 那些',
  'THOUGH',
  'conj. 虽然；可是',
  'THOUGHT',
  'n. 思考；思想；念头',
  'THREAD',
  'n. 线',
  'THREE',
  'num. 三',
  'THRILL',
  'n. & v. 兴奋；激动',
  'THROAT',
  'n. 喉咙',
  'THROUGH',
  'prep. 穿（通）过；从始至终',
  'THROW',
  'v. (threw, thrown) 投；掷；扔',
  'THUNDER',
  'n. & v. 雷声；打雷',
  'THUS',
  'adv. 这样；因而',
  'TIBET',
  'n. 西藏',
  'TIBETAN',
  'n. 西藏人；西藏语',
  'TICK',
  'vt. 作记号',
  'TICKET',
  'n. 票；卷',
  'TIDY',
  'adj. 整洁的；干净的',
  'TIGER',
  'n. 老虎',
  'TIGHT',
  'adj. 紧的',
  'TILL',
  'conj. & prep. 直到；直到…为止',
  'TIME',
  'n. 时间；时期；钟点；次；回',
  'TINY',
  'adj. 极小的；微小的',
  'TIRE',
  'vi. 使疲劳',
  'TIRED',
  'adj. 疲劳的；累的',
  'TISSUE',
  'n. （人、动植物的）组织；纸巾',
  'TITLE',
  'n. 标题；题目',
  'TOAST',
  'v. & n. 烤',
  'TOBACCO',
  'n. 烟草；烟叶',
  'TODAY',
  'adv. & n. 今天；现在；当前',
  'TOILET',
  'n. 厕所',
  'TOKYO',
  'n. 东京',
  'TOMATO',
  'n. 西红柿；番茄',
  'TOMB',
  'n. 坟墓',
  'TONGUE',
  'n. 舌；舌头',
  'TONIGHT',
  'adv. & n. 今晚；今夜',
  'TOOL',
  'n. 工具；器具',
  'TOOTH',
  'n. (复 teeth) 牙齿',
  'TOPIC',
  'n. 题目；话题',
  'TOTAL',
  'adj. 总数的；总括的；完全的；全然的',
  'TOTALLY',
  'adv. 总合地；完全地',
  'TOUCH',
  'vt. 触摸；接触',
  'TOUGH',
  'adj. 坚硬的；结实的；棘手的；难解的',
  'TOUR',
  'n. 参观；观光；旅行',
  'TOURISM',
  'n. 旅游业；观光',
  'TOURIST',
  'n. 旅行者；观光者',
  'TOWEL',
  'n. 毛巾',
  'TOWER',
  'n. 塔',
  'TOWN',
  'n. 城镇；城',
  'TRACK',
  'n. 轨道；田径',
  'TRACTOR',
  'n. 拖拉机',
  'TRADE',
  'n. 贸易',
  'TRAFFIC',
  'n. 交通；来往车辆',
  'TRAIN',
  'n. 火车',
  'TRAINER',
  'n. 训练人；教练',
  'TRAM',
  'n. 有轨电车',
  'TRAP',
  'n. 陷阱',
  'TRAVEL',
  'n. & vi. 旅行',
  'TREAT',
  'vt. 对待；看待',
  'TREE',
  'n. 树',
  'TREMBLE',
  'v. 颤抖',
  'TREND',
  'n. 趋势；倾向；动态',
  'TRIAL',
  'n. 审判；试验；试用',
  'TRICK',
  'n. 诡计；把戏',
  'TRIP',
  'n. 旅行；旅程',
  'TROOP',
  'n. 部队',
  'TROUBLE',
  'vt. 使苦恼；使忧虑；使麻烦',
  'TRUCK',
  'n. 卡车；运货车；车皮',
  'TRUE',
  'adj. 真的；真实的；忠诚的',
  'TRULY',
  'adv. 真正地；真实地',
  'TRUNK',
  'n. 树干；大箱子',
  'TRUST',
  'vt. 相信；信任；信赖',
  'TRUTH',
  'n. 真理；事实；真相；实际',
  'TUBE',
  'n. 管；管状物',
  'TUNE',
  'n. 曲调；曲子',
  'TUESDAY',
  'n. 星期二',
  'TURKEY',
  'n. 火鸡',
  'TURN',
  'v. 旋转；翻转；转变；转弯',
  'TURNING',
  'n. 拐弯处；拐角处',
  'TUTOR',
  'n. 家庭教师；私人教师；导师',
  'TWELFTH',
  'num. 第十二',
  'TWELVE',
  'num. 十二',
  'TWENTY',
  'num. 二十',
  'TWICE',
  'adv. 两次；两倍',
  'TWIN',
  'n. 双胞胎之一',
  'TWIST',
  'v. & n. 使弯曲；转动',
  'TYPE',
  'vt. 打字',
  'TYPICAL',
  'adj. 典型的；有代表性的；特有的',
  'TYPHOON',
  'n. 台风',
  'TYPIST',
  'n. 打字员',
  'TYRE',
  'n. 轮胎（美 tire）',
  'UGLY',
  'adj. 丑陋的；难看的',
  'UNABLE',
  'adj. 不能的；不能胜任的',
  'UNCLE',
  'n. 叔；伯；舅；姑夫；姨父',
  'UNDER',
  'adv. & prep. 在…下面；向…下面',
  'UNDO',
  'v. 解开；松开',
  'UNFAIR',
  'adj. 不公平的；不公正的',
  'UNFIT',
  'adj. 不合宜的；不相宜的',
  'UNFOLD',
  'vt. 展开；打开',
  'UNHAPPY',
  'adj. 不高兴的；伤心的',
  'UNIFORM',
  'n. 制服',
  'UNION',
  'n. 联合；联盟；工会',
  'UNIQUE',
  'adj. 惟一的；独一无二的',
  'UNIT',
  'n. 单元；单位',
  'UNITE',
  'v. 联合；团结',
  'UNKNOWN',
  'adj. 不知道的',
  'UNLESS',
  'conj. 如果不；除非',
  'UNLIKE',
  'prep. 不像；和…不同',
  'UNREST',
  'n. 不安；骚动',
  'UNSAFE',
  'adj. 不安全的；危险的',
  'UNTIL',
  'prep. & conj. 直到…为止',
  'UNTRUE',
  'adj. 不真实的；假的',
  'UNUSUAL',
  'adj. 不平常的；异常的',
  'UPON',
  'prep. 在……上面',
  'UPPER',
  'adj. 较高的；较上的',
  'UPSET',
  'adj. 心烦的；苦恼的',
  'UPWARD',
  'adv. 向上；往上',
  'URBAN',
  'adj. 城市的；都市的',
  'URGE',
  'v. 敦促；催促；力劝',
  'URGENT',
  'adj. 紧急的；紧迫的',
  'USED',
  'adj. 用过的；旧的；二手的',
  'USEFUL',
  'adj. 有用的；有益的',
  'USELESS',
  'adj. 无用的',
  'USER',
  'n. 使用者；用户',
  'USUAL',
  'adj. 通常的；平常的',
  'USUALLY',
  'adv. 通常；经常',
  'VACANT',
  'adj. 空缺的；未被占用的',
  'VAGUE',
  'adj. 含糊的；不明确的',
  'VAIN',
  'adj. 自负的；自视过高的；徒劳的；无效的',
  'VALID',
  'adj. 有效的；合理的；有根据的',
  'VALLEY',
  'n. 山谷；溪谷',
  'VALUE',
  'n. 价值；益处',
  'VANILLA',
  'n. 香草',
  'VARIETY',
  'n. 种种；种类',
  'VARIOUS',
  'adj. 各种各样的；不同的',
  'VASE',
  'n. （花）瓶；瓶饰',
  'VAST',
  'adj. 巨大的；广阔的',
  'VEAL',
  'n. （食用）小牛肉',
  'VEHICLE',
  'n. 交通工具；车辆',
  'VERSION',
  'n. 变体；变种；改写本',
  'VERY',
  'adv. 很；非常',
  'VEST',
  'n. 背心；内衣',
  'VICE',
  'n. 罪行；不道德行为',
  'VICTIM',
  'n. 受害者；牺牲品',
  'VICTORY',
  'n. 胜利',
  'VIDEO',
  'n. 录像；视频',
  'VIEW',
  'n. 看法；见解；风景；景色',
  'VIEWER',
  'n. 观看者',
  'VILLAGE',
  'n. 村庄；乡村',
  'VINEGAR',
  'n. 醋',
  'VIOLATE',
  'v. 违反（法律、协议等）；侵犯',
  'VIOLENT',
  'adj. 暴力的',
  'VIOLIN',
  'n. 小提琴',
  'VIRTUE',
  'n. 美德；正直的品行；德行',
  'VIRUS',
  'n. 病毒',
  'VISA',
  'n. 签证；背签',
  'VISIT',
  'n. & vt. 参观；访问；拜访',
  'VISITOR',
  'n. 访问者；参观者',
  'VISUAL',
  'adj. 视力的；视觉的',
  'VITAL',
  'adj. 必不可少的；对…极重要的',
  'VIVID',
  'adj. 生动的；逼真的；鲜明的',
  'VOICE',
  'n. 说话声；语态',
  'VOLCANO',
  'n. 火山',
  'VOTE',
  'vi. 选举；投票',
  'VOYAGE',
  'n. 航行；旅行',
  'WAGE',
  'n. 工资；工钱；报酬',
  'WAIST',
  'n. 腰；腰部；腰围',
  'WAIT',
  'vi. 等；等候',
  'WAITER',
  'n. （餐厅）男服务员',
  'WAKE',
  'v. (woke, woken) 醒来；叫醒',
  'WALK',
  'n. & v. 步行；散步',
  'WALKMAN',
  'n. 随身听',
  'WALL',
  'n. 墙',
  'WALLET',
  'n. （放钱、证件等的）皮夹',
  'WALNUT',
  'n. 核桃；胡桃',
  'WANDER',
  'vi. 漫游；游荡；漫步；流浪',
  'WANT',
  'vt. 想；想要；需要；必要',
  'WARD',
  'n. 保卫；看护；病房；收容所',
  'WARM',
  'adj. 暖和的；温暖的；热情的',
  'WARMTH',
  'n. 暖和；温暖',
  'WARN',
  'vt. 警告；预先通知',
  'WARNING',
  'n. 警报',
  'WASH',
  'n. 洗（涤）；冲洗；洗剂；泼溅；洗的衣服',
  'WASTE',
  'n. & vt. 浪费',
  'WATCH',
  'vt. 观看；注视；当心；注意',
  'WATER',
  'n. 水',
  'WAVE',
  'n. （热、光、声等的）波；波浪',
  'WAYSIDE',
  'adj. 路边的',
  'WEBSITE',
  'n. 网站',
  'WEAK',
  'adj. 差的；弱的；淡的',
  'WEALTH',
  'n. 财产；财富',
  'WEALTHY',
  'adj. 富的',
  'WEAR',
  'v. (wore, worn) 穿；戴',
  'WEATHER',
  'n. 天气',
  'WEDDING',
  'n. 婚礼；结婚',
  'WEED',
  'n. 杂草；野草',
  'WEEK',
  'n. 星期；周',
  'WEEKDAY',
  'n. 平日',
  'WEEKEND',
  'n. 周末',
  'WEEKLY',
  'adj. 每周的',
  'WEEP',
  'v. (wept, wept) 哭泣；流泪',
  'WEIGH',
  'vt. 称…的重量；重（若干）',
  'WEIGHT',
  'n. 重；重量',
  'WELCOME',
  'int., n. & v. 欢迎',
  'WELFARE',
  'n. 幸福；福利',
  'WELL',
  'adv. (better, best) 好；令人满意地；完全地',
  'WEST',
  'adj. (在)西的；向西的；从西来的',
  'WESTERN',
  'adj. 西方的；西部的',
  'WHALE',
  'n. 鲸',
  'WHAT',
  'pron. 什么；怎么样',
  'WHEAT',
  'n. 小麦',
  'WHEEL',
  'n. 轮；机轮',
  'WHEN',
  'conj. 当…的时候',
  'WHERE',
  'adv. 在哪里；往哪里',
  'WHETHER',
  'conj. 是否',
  'WHICH',
  'pron. 那（哪）一个；那（哪）一些',
  'WHILE',
  'conj. 在…的时候；和…同时',
  'WHISPER',
  'v. 低语；私下说',
  'WHISTLE',
  'n. 口哨；口哨声',
  'WHITE',
  'adj. 白色的',
  'WHOLE',
  'adj. 整个的',
  'WHOM',
  'pron. (who的宾格) 谁',
  'WHOSE',
  'pron. 谁的',
  'WIDE',
  'adj. 宽阔的',
  'WIFE',
  'n. 妻子',
  'WILD',
  'adj. 未开发的；荒凉的；野生的；野的',
  'WILL',
  'n. 意志；遗嘱',
  'WILLING',
  'adj. 乐意的；愿意的',
  'WIND',
  'n. 风',
  'WINDOW',
  'n. 窗户；计算机的窗',
  'WINDY',
  'adj. 有风的；多风的',
  'WINE',
  'n. 酒',
  'WING',
  'n. 机翼；翅膀',
  'WINNER',
  'n. 获胜者',
  'WINTER',
  'n. 冬天；冬季',
  'WIPE',
  'v. 擦；擦净；擦干',
  'WIRE',
  'n. 电线',
  'WISDOM',
  'n. 智慧',
  'WISE',
  'adj. 聪明的；英明的；有见识的',
  'WISH',
  'n. 愿望；祝愿',
  'WITH',
  'prep. 关于；带有；以；和；用；有',
  'WITHIN',
  'prep. 在……里面',
  'WITHOUT',
  'prep. 没有',
  'WITNESS',
  'v. & n. 目击者；见证人',
  'WOLF',
  'n. (复 wolves) 狼',
  'WOMAN',
  'n. (复 women) 妇女；女人',
  'WONDER',
  'v. 对…疑惑；感到惊奇；想知道',
  'WOOD',
  'n. 木头；木材；(复)树木；森林',
  'WOODEN',
  'adj. 木制的',
  'WOOL',
  'n. 羊毛；羊绒',
  'WOOLLEN',
  'adj. 羊毛的；羊毛制的',
  'WORD',
  'n. 词；单词；话',
  'WORK',
  'n. 工作；劳动；事情',
  'WORKDAY',
  'n. 工作日',
  'WORKER',
  'n. 工人；工作者',
  'WORKS',
  'n. 著作；作品',
  'WORLD',
  'n. 世界',
  'WORM',
  'n. 软体虫；蠕虫（尤指蚯蚓）',
  'WORN',
  'adj. 用坏的；用旧的；疲惫的',
  'WORRIED',
  'adj. 担心的；烦恼的',
  'WORRY',
  'n. & v. 烦恼；担忧；发怒；困扰',
  'WORSE',
  'adj. (bad的比较级) 更坏的',
  'WORST',
  'adj. (bad的最高级) 最坏的',
  'WORTH',
  'adj. 有…价值的；值得…的',
  'WORTHY',
  'adj. 值得的',
  'WOULD',
  'modal v. （will的过去时）将会；打算；想要；过去常常',
  'WOUND',
  'vt. 伤；伤害',
  'WOUNDED',
  'adj. 受伤的',
  'WRESTLE',
  'v. 摔跤',
  'WRINKLE',
  'n. 皱纹',
  'WRIST',
  'n. 手腕；腕关节',
  'WRITE',
  'v. (wrote, written) 写；书写；写作；著述',
  'WRITING',
  'n. 书写；写',
  'WRONG',
  'adj. 错误的；不正常的；有毛病的',
  'YARD',
  'n. 码；院子；场地',
  'YAWN',
  'v. 打哈欠',
  'YEAR',
  'n. 年',
  'YELL',
  'v. 叫喊；吼叫',
  'YELLOW',
  'adj. 黄色的',
  'YOGHURT',
  'n. 酸奶',
  'YOUNG',
  'adj. 年轻的',
  'YOUR',
  'pron. 你的；你们的',
  'YOURS',
  'pron. 你的；你们的',
  'YOUTH',
  'n. 青春；青年',
  'YUMMY',
  'adj. 很好吃的',
  'ZEBRA',
  'n. 斑马',
  'ZERO',
  'n. & num. 零；零度；零点',
  'ZIPPER',
  'n. 拉链',
  'ZONE',
  'n. 区域；范围',
  'ZOOM',
  'v. 快速移动；迅速前往；猛涨',
  'AGONIZE',
  'v. 使痛苦；苦苦思索',
  'ALLEGE',
  'v. 断言；指控；宣称',
  'ALLIED',
  'adj. 联合的；同盟的；相关的',
  'AMPLIFY',
  'v. 放大；增强；详述',
  'APTLY',
  'adv. 恰当地；贴切地',
  'ARTERY',
  'n. 动脉；干线；要道',
  'AVAIL',
  'v. 有益于；利用',
  'AXIAL',
  'adj. 轴的；轴向的',
  'AXIS',
  'n. 轴；轴线；轴心',
  'BADGE',
  'n. 徽章；标记；象征',
  'BAFFLE',
  'v. 使困惑；难倒',
  'BANKER',
  'n. 银行家；庄家',
  'BARON',
  'n. 男爵；巨头',
  'BATTER',
  'v. 连续猛击；殴打',
  'BEARING',
  'n. 举止；关系；方位；轴承',
  'BEMOAN',
  'v. 哀叹；惋惜；抱怨',
  'BLEAK',
  'adj. 荒凉的；凄凉的；无望的',
  'BLOND',
  'adj. 金发的',
  'BLUNT',
  'adj. 钝的；直率的',
  'BOSOM',
  'n. 胸；胸怀；内心',
  'BOWEL',
  'n. 肠；内部',
  'BRACKET',
  'n. 括号；等级',
  'BREEZY',
  'adj. 有微风的；轻松愉快的',
  'BREW',
  'v. 酿造；沏（茶）；酝酿',
  'BRIDLE',
  'n. 马勒；缰绳',
  'BROOD',
  'v. 沉思；孵蛋',
  'BRUTAL',
  'adj. 残暴的；冷酷的',
  'BUCK',
  'n. 美元；雄鹿',
  'BUFFALO',
  'n. 水牛；野牛',
  'BUGLE',
  'n. 军号；号角',
  'BUSHEL',
  'n. 蒲式耳（容量单位）',
  'BYPASS',
  'n. 旁路； bypass surgery 搭桥手术',
  'CALCIUM',
  'n. 钙',
  'CAVITY',
  'n. 洞；空腔；龋洞',
  'CENSOR',
  'n. 审查员',
  'CEREAL',
  'n. 谷物；谷类食品',
  'CHARTER',
  'n. 宪章；特许证',
  'CHERISH',
  'v. 珍爱；珍惜；怀抱',
  'CHORD',
  'n. 弦；和音',
  'CLAMP',
  'v. 夹紧；固定',
  'CLARITY',
  'n. 清楚；清晰；透明',
  'CLASP',
  'v. 紧握；扣紧',
  'CLATTER',
  'v. 发出咔嗒声',
  'CLIMAX',
  'n. 高潮；顶点',
  'CLOSET',
  'n. 壁橱；储藏室',
  'CLUTCH',
  'v. 紧抓；握住',
  'COARSE',
  'adj. 粗糙的；粗俗的',
  'COFFIN',
  'n. 棺材',
  'COLUMN',
  'n. 柱；纵队；专栏',
  'COMET',
  'n. 彗星',
  'COMPUTE',
  'v. 计算；估算',
  'CONCEIT',
  'n. 自负；自满；巧妙的比喻',
  'CONCISE',
  'adj. 简明的；简洁的',
  'CONSENT',
  'n. & v. 同意；赞同',
  'CONSOLE',
  'v. 安慰；抚慰',
  'CONVENE',
  'v. 召集；集合',
  'CONVICT',
  'v. 定罪；证明有罪',
  'CORDIAL',
  'adj. 热诚的；亲切的',
  'CORPS',
  'n. 军团；特殊部队；团体',
  'CORRODE',
  'v. 腐蚀；侵蚀',
  'COSMIC',
  'adj. 宇宙的；巨大的',
  'COSMOS',
  'n. 宇宙；秩序',
  'CRADLE',
  'n. 摇篮；发源地',
  'CRANK',
  'n. 曲柄；怪人',
  'CRIPPLE',
  'v. 使残废；使瘫痪',
  'CROOKED',
  'adj. 弯曲的；不诚实的',
  'CRUCIAL',
  'adj. 至关重要的；决定性的',
  'CRUST',
  'n. 外壳；面包皮；地壳',
  'CRYSTAL',
  'n. 水晶；晶体',
  'CUCKOO',
  'n. 布谷鸟；杜鹃',
  'CURLY',
  'adj. 卷曲的',
  'CYNICAL',
  'adj. 愤世嫉俗的；悲观的',
  'DATUM',
  'n. 数据；资料（复数 data）',
  'DAZZLE',
  'v. 使目眩；使惊叹',
  'DEALER',
  'n. 经销商；商人',
  'DEAN',
  'n. 院长；系主任；教务长',
  'DECIMAL',
  'adj. 十进制的',
  'DECODE',
  'v. 解码；破译',
  'DECREE',
  'n. 法令；政令',
  'DEDUCT',
  'v. 扣除；减去',
  'DEFAULT',
  'n. 默认；违约',
  'DEFICIT',
  'n. 赤字；亏损；不足',
  'DEFLECT',
  'v. 使偏斜；转移',
  'DEGRADE',
  'v. 使降级；使退化；贬低',
  'DENOTE',
  'v. 表示；意味着',
  'DEPICT',
  'v. 描绘；描述',
  'DERAIL',
  'v. 使脱轨；使偏离轨道',
  'DESCENT',
  'n. 下降；斜坡；出身',
  'DESTINE',
  'v. 注定；预定',
  'DETACH',
  'v. 分开；拆卸；派遣',
  'DETAIN',
  'v. 拘留；耽搁',
  'DEVOUR',
  'v. 吞食；贪婪地看或听',
  'DIESEL',
  'n. 柴油；柴油车',
  'DIFFUSE',
  'v. 扩散；传播',
  'DILUTE',
  'v. 稀释；冲淡',
  'DISABLE',
  'v. 使无能；使残疾；禁用',
  'DISCERN',
  'v. 辨别；觉察',
  'DISDAIN',
  'n. & v. 蔑视；鄙视',
  'DISMAY',
  'n. & v. 沮丧；惊慌',
  'DISRUPT',
  'v. 打乱；破坏；使中断',
  'DISTILL',
  'v. 蒸馏；提取；提炼',
  'DISTORT',
  'v. 扭曲；歪曲',
  'DIVERGE',
  'v. 分歧；偏离；分叉',
  'DIVINE',
  'adj. 神圣的；非凡的',
  'DOCK',
  'n. 码头；被告席',
  'DODGE',
  'v. 躲闪；避开',
  'DOLE',
  'n. 救济金',
  'DOLPHIN',
  'n. 海豚',
  'DOMAIN',
  'n. 领域；范围；领地',
  'DOME',
  'n. 圆顶；穹顶',
  'DONOR',
  'n. 捐赠者；供体',
  'DOVE',
  'n. 鸽子；鸽派人物',
  'DRASTIC',
  'adj. 激烈的；猛烈的',
  'DREAD',
  'n. & v. 恐惧；担忧',
  'DROUGHT',
  'n. 干旱；旱灾',
  'DUKE',
  'n. 公爵',
  'DUTIFUL',
  'adj. 尽职的；恭顺的',
  'DWELLER',
  'n. 居民；居住者',
  'ECHO',
  'n. 回声；回响',
  'EJECT',
  'v. 喷出；弹出；驱逐',
  'ELASTIC',
  'adj. 弹性的；灵活的',
  'ELBOW',
  'n. 肘部；弯头',
  'ELEVATE',
  'v. 提升；举起；鼓舞',
  'ELICIT',
  'v. 引出；诱出',
  'ELITE',
  'n. 精英；上层人士',
  'EMBARK',
  'v. 上船；着手；从事',
  'EMBED',
  'v. 嵌入；埋入',
  'EMBODY',
  'v. 体现；包含；使具体化',
  'EMERGE',
  'v. 浮现；出现；显露',
  'ENCHANT',
  'v. 使陶醉；使着迷；施魔法',
  'ENDORSE',
  'v. 支持；认可；背书',
  'ENGROSS',
  'v. 使全神贯注；独占',
  'ENROLL',
  'v. 注册；登记；招收',
  'ENTITLE',
  'v. 使有资格；给予权利；给...命名',
  'ENTITY',
  'n. 实体；存在',
  'ENTREAT',
  'v. 恳求；乞求',
  'EPISODE',
  'n. 插曲；片段；一集',
  'EPOCH',
  'n. 纪元；时期；新时代',
  'EQUATOR',
  'n. 赤道',
  'ERRAND',
  'n. 差事；跑腿',
  'ESCORT',
  'n. 护送者；护卫队',
  'ETERNAL',
  'adj. 永恒的；永久的',
  'ETHNIC',
  'adj. 民族的；种族的',
  'EVOLVE',
  'v. 进化；演变；发展',
  'EXCEL',
  'v. 擅长；优于',
  'EXCESS',
  'n. 过量；过度',
  'EXCLUDE',
  'v. 排除；排斥',
  'EXILE',
  'n. & v. 流放；放逐',
  'EXPEL',
  'v. 驱逐；开除；排出',
  'EXPEND',
  'v. 花费；消耗',
  'EXPIRE',
  'v. 到期；终止；断气',
  'EXTINCT',
  'adj. 灭绝的；熄灭的',
  'FACET',
  'n. 方面；（宝石的）刻面',
  'FACTION',
  'n. 派别；小集团',
  'FACULTY',
  'n. 全体教员；能力；院系',
  'FAKE',
  'adj. 假的；伪造的',
  'FAMINE',
  'n. 饥荒；严重短缺',
  'FATAL',
  'adj. 致命的；灾难性的',
  'FATIGUE',
  'n. 疲劳；劳累',
  'FEEBLE',
  'adj. 虚弱的；微弱的',
  'FERROUS',
  'adj. 铁的；含铁的',
  'FILTH',
  'n. 污秽；肮脏',
  'FINITE',
  'adj. 有限的；限定的',
  'FISCAL',
  'adj. 财政的；国库的',
  'FISSION',
  'n. 裂变；分裂',
  'FIXTURE',
  'n. 固定装置；固定物',
  'FLAKE',
  'n. 薄片；雪花',
  'FLANK',
  'n. 侧翼；侧面',
  'FLANNEL',
  'n. 法兰绒',
  'FLAP',
  'v. 拍打；摆动',
  'FLARE',
  'v. 燃烧；突然发怒',
  'FLASK',
  'n. 烧瓶；长颈瓶',
  'FLATTER',
  'v. 奉承；使高兴',
  'FLAW',
  'n. 瑕疵；缺陷',
  'FLEE',
  'v. 逃跑；逃离',
  'FLING',
  'v. 投掷；抛',
  'FLIP',
  'v. 轻掷；翻转',
  'FLOCK',
  'n. 一群；羊群',
  'FLUENCY',
  'n. 流利；流畅',
  'FLUSH',
  'v. 冲洗；脸红',
  'FLUTTER',
  'v. 振翅；飘动；悸动',
  'FLUX',
  'n. 流量；不断变化；通量',
  'FOAM',
  'n. 泡沫；泡沫材料',
  'FOIL',
  'n. 箔；陪衬',
  'FORE',
  'adj. 前面的；在前部的',
  'FORESEE',
  'v. 预见；预知',
  'FORGE',
  'v. 锻造；伪造；稳步前进',
  'FORMAL',
  'adj. 正式的；形式上的',
  'FORMAT',
  'n. 格式；版式',
  'FORSAKE',
  'v. 放弃；抛弃',
  'FORUM',
  'n. 论坛；讨论会',
  'FOSSIL',
  'n. 化石；守旧派',
  'FOSTER',
  'v. 促进；培养；收养',
  'FOUL',
  'adj. 肮脏的；邪恶的',
  'FOWL',
  'n. 家禽；禽肉',
  'FRAGILE',
  'adj. 脆弱的；易碎的',
  'FRANTIC',
  'adj. 发狂的；狂乱的',
  'FRAUD',
  'n. 欺诈；骗子',
  'FREIGHT',
  'n. 货物；运费',
  'FRESHEN',
  'v. 使新鲜；使清爽',
  'FRET',
  'v. 烦恼；担心；磨损',
  'FRINGE',
  'n. 边缘；刘海',
  'FROCK',
  'n. 女裙；僧袍',
  'FURIOUS',
  'adj. 狂怒的；猛烈的',
  'FURNISH',
  'v. 提供；装备；布置',
  'FUSION',
  'n. 融合；核聚变',
  'FUSS',
  'n. 大惊小怪；忙乱',
  'GALAXY',
  'n. 星系；银河',
  'GALLERY',
  'n. 画廊；美术馆',
  'GAMBLE',
  'v. & n. 赌博；冒险',
  'GARAGE',
  'n. 车库；汽车修理厂',
  'GARBAGE',
  'n. 垃圾；废话',
  'GARLIC',
  'n. 大蒜',
  'GARMENT',
  'n. 服装；外衣',
  'GASP',
  'v. & n. 喘气；倒抽气',
  'GAUGE',
  'n. 测量仪器；标准尺寸',
  'GEAR',
  'n. 齿轮；设备；档位',
  'GENETIC',
  'adj. 遗传的；基因的',
  'GENIUS',
  'n. 天才；天赋',
  'GEOLOGY',
  'n. 地质学',
  'GESTURE',
  'n. 手势；姿态',
  'GINGER',
  'n. 姜；姜黄色',
  'GLAND',
  'n. 腺体',
  'GLARE',
  'v. 怒视；发出强光',
  'GLEAM',
  'v. 闪烁；发光',
  'GLIDER',
  'n. 滑翔机；滑行者',
  'GLOOM',
  'n. 忧郁；黑暗',
  'GLOOMY',
  'adj. 阴暗的；忧郁的',
  'GLORIFY',
  'v. 赞美；颂扬；使更美',
  'GLOW',
  'v. 发光；发热；容光焕发',
  'GNAW',
  'v. 啃；咬；侵蚀',
  'GODDESS',
  'n. 女神',
  'GORILLA',
  'n. 大猩猩',
  'GOSSIP',
  'n. 流言蜚语；闲聊',
  'GOWN',
  'n. 长袍；礼服',
  'GRANITE',
  'n. 花岗岩',
  'GRAVEL',
  'n. 砾石；碎石',
  'GRAZE',
  'v. 放牧；擦伤',
  'GREED',
  'n. 贪婪；贪心',
  'GRIM',
  'adj. 严峻的；冷酷的',
  'GRIND',
  'v. 磨碎；碾磨',
  'GRIN',
  'v. & n. 咧嘴笑；露齿笑',
  'GRIP',
  'n. 紧握；控制',
  'GROAN',
  'v. & n. 呻吟；抱怨',
  'GROOVE',
  'n. 沟槽；凹槽',
  'GROPE',
  'v. 摸索；摸索着走',
  'GROSS',
  'adj. 总的；粗俗的；严重的',
  'GROVE',
  'n. 小树林；树丛',
  'GROWL',
  'v. & n. 咆哮；隆隆响',
  'GRUNT',
  'v. & n. 咕噜声；嘟囔',
  'GUILT',
  'n. 内疚；罪责',
  'GUITAR',
  'n. 吉他',
  'GUTTER',
  'n. 排水沟；贫民区',
  'HACK',
  'v. 砍；乱劈；侵入（电脑）',
  'HAIL',
  'v. 欢呼；致敬；下冰雹',
  'HALVE',
  'v. 减半；对分',
  'HAMPER',
  'v. 妨碍；阻碍',
  'HANDGUN',
  'n. 手枪',
  'HANDOUT',
  'n. 讲义；施舍物',
  'HARDY',
  'adj. 强壮的；耐寒的',
  'HARP',
  'n. 竖琴',
  'HARSH',
  'adj. 严厉的；严酷的',
  'HASTEN',
  'v. 催促；加速；急忙',
  'HATRED',
  'n. 仇恨；憎恨',
  'HAUGHTY',
  'adj. 傲慢的；高傲的',
  'HAUNT',
  'v. 常出没于；萦绕',
  'HAWK',
  'n. 鹰；鹰派人物',
  'HAZARD',
  'n. 危险；风险',
  'HEADING',
  'n. 标题；标题方向',
  'HEARTH',
  'n. 炉边；壁炉',
  'HEARTY',
  'adj. 热诚的；丰盛的；健壮的',
  'HEAVE',
  'v. 举起；起伏；用力拉',
  'HEAVEN',
  'n. 天堂；天空；极乐',
  'HERALD',
  'n. 先驱；报信者',
  'HIJACK',
  'v. 劫持；拦路抢劫',
  'HIKE',
  'n. & v. 远足；徒步；提高',
  'HINDER',
  'v. 阻碍；妨碍',
  'HINGE',
  'n. 铰链；合页',
  'HISS',
  'v. & n. 嘶嘶声；发嘘声',
  'HOARSE',
  'adj. 嘶哑的；沙哑的',
  'HOIST',
  'v. 升起；吊起',
  'HOLLOW',
  'adj. 空的；空洞的；凹陷的',
  'HOMELY',
  'adj. 平凡的；不好看的；家常的',
  'HORIZON',
  'n. 地平线；视野',
  'HORN',
  'n. 角；号角；喇叭',
  'HOSE',
  'n. 软管；长筒袜',
  'HOSTAGE',
  'n. 人质',
  'HOUND',
  'n. 猎犬',
  'HOVER',
  'v. 盘旋；徘徊',
  'HUDDLE',
  'v. 挤作一团；蜷缩',
  'HULL',
  'n. 船体；外壳',
  'HURL',
  'v. 猛投；猛摔；大叫',
  'HUSH',
  'v. & n. 安静；沉默',
  'HUSTLE',
  'v. 催促；猛推；忙碌',
  'HYMN',
  'n. 赞美诗；圣歌',
  'IDEALLY',
  'adv. 理想地；理论上',
  'IDIOT',
  'n. 白痴；蠢人',
  'IGNITE',
  'v. 点燃；引发；着火',
  'IMMERSE',
  'v. 沉浸；使浸入',
  'IMMUNE',
  'adj. 免疫的；不受影响的',
  'IMPAIR',
  'v. 损害；削弱',
  'IMPART',
  'v. 传授；告知；赋予',
  'IMPETUS',
  'n. 推动力；促进',
  'IMPLORE',
  'v. 恳求；哀求',
  'IMPOSE',
  'v. 强加；征收；施加',
  'IMPULSE',
  'n. 冲动；脉冲',
  'INCUR',
  'v. 招致；遭受；引起',
  'INDOOR',
  'adj. 室内的',
  'INDUCE',
  'v. 诱导；引起；劝诱',
  'INFANT',
  'n. 婴儿；幼儿',
  'INFER',
  'v. 推断；推论',
  'INFLICT',
  'v. 造成；施加（伤害等）',
  'INHABIT',
  'v. 居住于；栖息于',
  'INHALE',
  'v. 吸入；吸气',
  'INHERIT',
  'v. 继承；经遗传获得',
  'INHIBIT',
  'v. 抑制；约束；阻止',
  'INJECT',
  'v. 注射；注入',
  'INLET',
  'n. 进口；水湾',
  'INPUT',
  'n. 输入；投入',
  'INSANE',
  'adj. 疯狂的；精神错乱的',
  'INSIGHT',
  'n. 洞察力；洞见',
  'INSTALL',
  'v. 安装；任命',
  'INSURER',
  'n. 保险公司；承保人',
  'INTACT',
  'adj. 完整无缺的；未受损伤的',
  'INTENSE',
  'adj. 强烈的；激烈的',
  'INTERIM',
  'adj. 临时的；中间的',
  'INVERT',
  'v. 颠倒；翻转',
  'INVEST',
  'v. 投资；投入',
  'INVOICE',
  'n. 发票；发货单',
  'INVOLVE',
  'v. 包含；牵涉；参与',
  'INWARD',
  'adj. 向内的；内心的',
  'ISLAM',
  'n. 伊斯兰教',
  'ISLE',
  'n. 小岛；岛',
  'IVORY',
  'n. 象牙；象牙色',
  'JACK',
  'n. 千斤顶；杰克',
  'JAIL',
  'n. 监狱',
  'JEAN',
  'n. 牛仔裤',
  'JELLY',
  'n. 果冻；果酱',
  'JERK',
  'v. & n. 猛拉；急动',
  'JINGLE',
  'v. & n. 叮当声；广告歌曲',
  'JUPITER',
  'n. 木星',
  'JURY',
  'n. 陪审团',
  'KEEN',
  'adj. 热心的；敏锐的；锋利的',
  'KERNEL',
  'n. 核心；内核；果仁',
  'KIDNAP',
  'v. 绑架；诱拐',
  'KINETIC',
  'adj. 动力的；运动的',
  'KNIGHT',
  'n. 骑士；爵士',
  'KNOB',
  'n. 门把手；旋钮；瘤',
  'LACE',
  'n. 蕾丝；花边；鞋带',
  'LANE',
  'n. 车道；小巷；航线',
  'LASH',
  'v. 猛击；鞭打；抨击',
  'LATENT',
  'adj. 潜在的；潜伏的',
  'LATTICE',
  'n. 格子；晶格',
  'LAWN',
  'n. 草坪；草地',
  'LAWSUIT',
  'n. 诉讼',
  'LAYMAN',
  'n. 外行；门外汉',
  'LAYOUT',
  'n. 布局；安排',
  'LEAKAGE',
  'n. 泄漏；渗漏',
  'LEASE',
  'n. 租约；租期',
  'LENS',
  'n. 镜头；透镜',
  'LEOPARD',
  'n. 豹子',
  'LESSEN',
  'v. 减少；减轻',
  'LEST',
  'conj. 以免；唯恐',
  'LEVER',
  'n. 杠杆；手段',
  'LIABLE',
  'adj. 有责任的；易于...的',
  'LIBERAL',
  'adj. 自由的；慷慨的；开明的',
  'LIMB',
  'n. 肢；臂；腿；树枝',
  'LIMP',
  'v. 跛行；蹒跚',
  'LINEAR',
  'adj. 线性的；直线的',
  'LINER',
  'n. 班轮；衬里',
  'LINGER',
  'v. 逗留；徘徊；缠绵',
  'LITERAL',
  'adj. 字面上的；逐字的',
  'LOBBY',
  'n. 大厅；游说团体',
  'LODGING',
  'n. 住处；寄宿',
  'LOFTY',
  'adj. 高耸的；崇高的',
  'LOOM',
  'v. 隐隐出现；逼近',
  'LOOSELY',
  'adv. 宽松地；松散地',
  'LUMP',
  'n. 块；肿块',
  'LUNAR',
  'adj. 月亮的；月球的',
  'LURE',
  'v. 吸引；引诱',
  'LUXURY',
  'n. 奢侈；奢侈品',
  'MAGNET',
  'n. 磁铁；有吸引力的人/物',
  'MAGNIFY',
  'v. 放大；夸大',
  'MAIDEN',
  'adj. 首次的；未婚的',
  'MAJESTY',
  'n. 威严；陛下',
  'MALICE',
  'n. 恶意；怨恨',
  'MALL',
  'n. 购物中心',
  'MAMMAL',
  'n. 哺乳动物',
  'MANSION',
  'n. 豪宅；大厦',
  'MANUAL',
  'adj. 手工的；体力的',
  'MARGIN',
  'n. 边缘；利润；余裕',
  'MARINE',
  'adj. 海洋的',
  'MARSHAL',
  'n. 元帅；执法官',
  'MARTYR',
  'n. 烈士；殉道者',
  'MARVEL',
  'v. 感到惊奇',
  'MAST',
  'n. 桅杆；天线塔',
  'MEADOW',
  'n. 草地；牧场',
  'MEDIATE',
  'v. 调解；调停',
  'MELODY',
  'n. 旋律；悦耳的音乐',
  'MEMO',
  'n. 备忘录',
  'MENACE',
  'n. 威胁；危险',
  'MERCURY',
  'n. 汞；水银；水星',
  'MERGE',
  'v. 合并；融合',
  'MERIT',
  'n. 价值；优点',
  'MESH',
  'n. 网眼；网孔；网络',
  'MIGHTY',
  'adj. 强大的；巨大的',
  'MIGRANT',
  'n. 移民；迁徙动物',
  'MIGRATE',
  'v. 迁移；移居',
  'MILKY',
  'adj. 乳白色的；奶制的',
  'MINIMAL',
  'adj. 最小的；最低限度的',
  'MINING',
  'n. 采矿；矿业',
  'MINOR',
  'adj. 较小的；次要的',
  'MINT',
  'n. 薄荷；造币厂',
  'MIRACLE',
  'n. 奇迹',
  'MISER',
  'n. 守财奴；吝啬鬼',
  'MISERY',
  'n. 痛苦；悲惨',
  'MISLEAD',
  'v. 误导；欺骗',
  'MITTEN',
  'n. 连指手套；手套',
  'MIXER',
  'n. 搅拌机；混音器',
  'MOCK',
  'v. 嘲笑；模仿',
  'MODESTY',
  'n. 谦虚；适度',
  'MONARCH',
  'n. 君主；帝王',
  'MONK',
  'n. 僧侣；修道士',
  'MOOR',
  'v. 使停泊；系泊',
  'MORTAL',
  'adj. 终有一死的；致命的',
  'MOSQUE',
  'n. 清真寺',
  'MOTEL',
  'n. 汽车旅馆',
  'MOTIVE',
  'n. 动机；目的',
  'MOULD',
  'n. 模具；霉菌（同mold）',
  'MUSE',
  'v. 沉思；冥想',
  'MUTE',
  'adj. 沉默的；哑的',
  'MUTTER',
  'v. & n. 嘟囔；嘀咕',
  'MUTUAL',
  'adj. 相互的；共同的',
  'MYSTERY',
  'n. 神秘；谜',
  'MYTH',
  'n. 神话；虚构的事',
  'NAPKIN',
  'n. 餐巾；纸巾',
  'NASTY',
  'adj. 令人讨厌的；恶劣的；严重的',
  'NEGLECT',
  'v. & n. 忽视；疏忽',
  'NEUTRAL',
  'adj. 中立的；中性的；不偏不倚的',
  'NEUTRON',
  'n. 中子',
  'NICKEL',
  'n. 镍；五分硬币',
  'NOMINAL',
  'adj. 名义上的；象征性的；标称的',
  'NORM',
  'n. 规范；标准；准则',
  'NOTABLE',
  'adj. 显著的；著名的',
  'NOTIFY',
  'v. 通知；告知',
  'NOTION',
  'n. 概念；看法；念头',
  'NOURISH',
  'v. 滋养；养育；怀有',
  'NOVELTY',
  'n. 新奇；新颖；新奇事物',
  'NUCLEUS',
  'n. 原子核；细胞核；核心',
  'NURTURE',
  'v. 养育；培养；滋养',
  'OATH',
  'n. 誓言；誓约',
  'OBESITY',
  'n. 肥胖',
  'OBLIGE',
  'v. 迫使；使感激；帮...的忙',
  'OBSCURE',
  'adj. 模糊的；晦涩的；不出名的',
  'OFFSET',
  'v. 抵消；弥补',
  'OLIVE',
  'n. 橄榄；橄榄色',
  'ONGOING',
  'adj. 持续进行的',
  'OPAQUE',
  'adj. 不透明的；难懂的',
  'OPIUM',
  'n. 鸦片',
  'OPPRESS',
  'v. 压迫；压抑',
  'OPTIMUM',
  'adj. 最佳的；最适宜的',
  'ORCHARD',
  'n. 果园',
  'ORIENT',
  'v. 使适应；确定方向',
  'OUTCRY',
  'n. 强烈抗议；公开反对',
  'OUTDATE',
  'v. 使过时',
  'OUTDOOR',
  'adj. 户外的；露天的',
  'OUTFIT',
  'n. 全套服装；装备',
  'OUTLAW',
  'n. 亡命之徒；逃犯',
  'OUTLIVE',
  'v. 比...活得长；经受住',
  'OUTPOST',
  'n. 前哨；偏远定居点',
  'OUTRAGE',
  'n. 愤怒；暴行',
  'OUTSET',
  'n. 开始；开端',
  'OVERALL',
  'adj. 全面的；总体的',
  'OVERLAP',
  'v. & n. 重叠',
  'OVERT',
  'adj. 公开的；明显的',
  'OXIDE',
  'n. 氧化物',
  'OXIDIZE',
  'v. 氧化；使生锈',
  'OYSTER',
  'n. 牡蛎',
  'OZONE',
  'n. 臭氧',
  'PACT',
  'n. 协定；条约',
  'PANT',
  'v. & n. 喘息；气喘吁吁',
  'PANTHER',
  'n. 美洲豹；黑豹',
  'PANTRY',
  'n. 食品储藏室',
  'PARADOX',
  'n. 悖论；自相矛盾的说法',
  'PARTIAL',
  'adj. 部分的；偏袒的',
  'PASTIME',
  'n. 消遣；娱乐',
  'PASTURE',
  'n. 牧场；草地',
  'PATRIOT',
  'n. 爱国者',
  'PATROL',
  'v. & n. 巡逻；巡查',
  'PATRON',
  'n. 赞助人；老顾客',
  'PAYROLL',
  'n. 工资单；工资总额',
  'PEACOCK',
  'n. 孔雀',
  'PEAK',
  'n. 山峰；顶点',
  'PEDAL',
  'n. 踏板',
  'PEDLAR',
  'n. 小贩；流动商贩',
  'PEEL',
  'v. 削皮；剥落',
  'PENALTY',
  'n. 处罚；罚球',
  'PENGUIN',
  'n. 企鹅',
  'PERCH',
  'v. 栖息；停留；置于高处',
  'PERIL',
  'n. 危险；风险',
  'PERISH',
  'v. 死亡；消亡；毁灭',
  'PERPLEX',
  'v. 使困惑；使复杂',
  'PETTY',
  'adj. 琐碎的；小气的',
  'PIER',
  'n. 码头；桥墩',
  'PIERCE',
  'v. 刺穿；穿透；穿洞',
  'PILGRIM',
  'n. 朝圣者；旅行者',
  'PIOUS',
  'adj. 虔诚的；虔诚的',
  'PIRATE',
  'n. 海盗；盗版者',
  'PISTON',
  'n. 活塞',
  'PLAGUE',
  'n. 瘟疫；灾祸',
  'PLASTER',
  'n. 石膏；灰泥；膏药',
  'PLATEAU',
  'n. 高原；平稳期',
  'PLEA',
  'n. 恳求；申诉；辩护',
  'PLEDGE',
  'n. & v. 誓言；保证',
  'PLOUGH',
  'n. 犁',
  'PLUCK',
  'v. 拔；采摘；弹奏',
  'PLUMP',
  'adj. 丰满的；圆胖的',
  'PLUNDER',
  'v. & n. 掠夺；抢劫',
  'PLUNGE',
  'v. 投入；陷入；猛降',
  'POETRY',
  'n. 诗歌；诗意',
  'POLAR',
  'adj. 极地的；极性的；正好相反的',
  'POLL',
  'n. 民意调查；投票',
  'POLYMER',
  'n. 聚合物',
  'PONY',
  'n. 矮种马；小马',
  'PONDER',
  'v. 沉思；考虑',
  'PORCH',
  'n. 门廊；走廊',
  'PORE',
  'n. 毛孔；气孔',
  'PORTRAY',
  'v. 描绘；扮演；刻画',
  'POSE',
  'v. 摆姿势；造成；提出',
  'POSTAL',
  'adj. 邮政的；邮局的',
  'POULTRY',
  'n. 家禽；禽肉',
  'PREACH',
  'v. 布道；宣讲；提倡',
  'PRECEDE',
  'v. 先于；在...之前发生',
  'PREFACE',
  'n. 前言；序言',
  'PREMISE',
  'n. 前提；假设',
  'PREMIUM',
  'n. 保险费；奖金；额外费用',
  'PRESIDE',
  'v. 主持；担任主席',
  'PRESUME',
  'v. 假定；推测；擅自',
  'PRETEXT',
  'n. 借口；托词',
  'PREVAIL',
  'v. 盛行；占优势；说服',
  'PREY',
  'n. 猎物',
  'PRICK',
  'v. 刺；扎',
  'PRIEST',
  'n. 牧师；神父',
  'PRISM',
  'n. 棱镜',
  'PRIVACY',
  'n. 隐私；私密',
  'PROBE',
  'n. 探针；调查',
  'PROLONG',
  'v. 延长；拖延',
  'PROMPT',
  'adj. 迅速的；及时的',
  'PRONE',
  'adj. 易于...的；有...倾向的',
  'PRONOUN',
  'n. 代词',
  'PROPEL',
  'v. 推动；驱动',
  'PROPHET',
  'n. 预言家；先知',
  'PROTEIN',
  'n. 蛋白质',
  'PROTEST',
  'n. & v. 抗议；反对',
  'PROTON',
  'n. 质子',
  'PROVERB',
  'n. 谚语；格言',
  'PROVOKE',
  'v. 激怒；挑衅；引发',
  'PRUDENT',
  'adj. 谨慎的；明智的',
  'PUFF',
  'v. & n. 喷；喘息；膨胀',
  'PULLEY',
  'n. 滑轮；滑车',
  'PUMPKIN',
  'n. 南瓜',
  'PUNCH',
  'v. 拳打；穿孔',
  'PUPPY',
  'n. 小狗；幼犬',
  'PURIFY',
  'v. 净化；提纯',
  'PURITY',
  'n. 纯净；纯洁；纯度',
  'PURSUIT',
  'n. 追求；寻找；追赶',
  'PYJAMAS',
  'n. 睡衣',
  'QUARTZ',
  'n. 石英',
  'QUEER',
  'adj. 奇怪的；古怪的',
  'QUENCH',
  'v. 解渴；熄灭；压制',
  'QUEST',
  'n. 探索；寻求',
  'QUICKEN',
  'v. 加快；使活跃',
  'QUOTA',
  'n. 配额；定额',
  'RACKET',
  'n. 球拍；喧闹；非法勾当',
  'RADAR',
  'n. 雷达',
  'RADIAL',
  'adj. 辐射状的；半径的',
  'RADIANT',
  'adj. 发光的；容光焕发的',
  'RADIATE',
  'v. 辐射；散发',
  'RADICAL',
  'adj. 根本的；激进的',
  'RADIUS',
  'n. 半径',
  'RAISIN',
  'n. 葡萄干',
  'RALLY',
  'v. & n. 集合；恢复； rally',
  'RAMBLE',
  'v. & n. 闲逛；漫谈；漫游',
  'RANCH',
  'n. 牧场；农场',
  'RAPTURE',
  'n. 狂喜；欢天喜地',
  'RASCAL',
  'n. 流氓；小坏蛋',
  'RASH',
  'adj. 轻率的；鲁莽的',
  'RATING',
  'n. 评级；收视率；评分',
  'RATTLE',
  'v. & n. 发出咔嗒声；使紧张',
  'REACTOR',
  'n. 反应器；反应堆',
  'READILY',
  'adv. 乐意地；容易地',
  'REAP',
  'v. 收割；收获',
  'REAR',
  'n. 后部；后面',
  'REBEL',
  'n. 反叛者；造反者',
  'REBUKE',
  'v. & n. 指责；斥责',
  'RECALL',
  'v. 回忆；召回',
  'RECEDE',
  'v. 退去；后退；减弱',
  'RECKON',
  'v. 认为；估计；计算',
  'RECLAIM',
  'v. 收回；开垦；改造',
  'RECRUIT',
  'v. 招聘；招募',
  'RECTIFY',
  'v. 改正；纠正；整流',
  'RECUR',
  'v. 再发生；重现',
  'REED',
  'n. 芦苇；芦笛',
  'REEF',
  'n. 礁石；暗礁',
  'REEL',
  'n. 卷轴；线轴',
  'REFINE',
  'v. 精炼；提纯；改进',
  'REFLEX',
  'n. 反射；反应能力',
  'REFRAIN',
  'v. 克制；抑制',
  'REFUGE',
  'n. 避难所；庇护',
  'REFUGEE',
  'n. 难民',
  'REFUND',
  'n. & v. 退款',
  'REFUTE',
  'v. 反驳；驳斥',
  'REGAIN',
  'v. 恢复；重新获得',
  'REGIME',
  'n. 政权；政体；管理制度',
  'REIGN',
  'n. 统治；任期',
  'REIN',
  'n. 缰绳；控制',
  'REJOICE',
  'v. 欣喜；高兴',
  'RELEASE',
  'v. & n. 释放；发布；释放',
  'RELIC',
  'n. 遗迹；遗物；圣骨',
  'RELIEVE',
  'v. 缓解；解除；接替',
  'REMEDY',
  'n. 补救办法；治疗法',
  'REMNANT',
  'n. 残余；剩余物',
  'RENDER',
  'v. 使成为；提供；渲染',
  'RENTAL',
  'n. 租赁；租金',
  'REPEAL',
  'v. & n. 废除；撤销',
  'REPEL',
  'v. 击退；排斥；使反感',
  'REPTILE',
  'n. 爬行动物',
  'RESENT',
  'v. 怨恨；愤恨',
  'RESIDE',
  'v. 居住；存在于',
  'RESOLVE',
  'v. 解决；决心；决定',
  'RESORT',
  'v. 诉诸；常去',
  'RESTORE',
  'v. 恢复；修复；归还',
  'RESUME',
  'v. 重新开始；恢复',
  'RETAIL',
  'n. & v. 零售',
  'RETAIN',
  'v. 保留；保持；记住',
  'RETARD',
  'v. 延迟；阻碍',
  'RETORT',
  'v. & n. 反驳；回嘴',
  'RETREAT',
  'v. & n. 撤退；退却；隐居',
  'REUNION',
  'n. 团聚；重聚',
  'REVENGE',
  'n. & v. 报复；复仇',
  'REVENUE',
  'n. 收入；税收',
  'REVERSE',
  'v. 颠倒；反转；撤销',
  'REVISE',
  'v. 修订；修正；复习',
  'REVIVE',
  'v. 复兴；复活；恢复',
  'REVOLVE',
  'v. 旋转；围绕；反复思考',
  'RHYTHM',
  'n. 节奏；韵律',
  'RIGOR',
  'n. 严格；严酷；严谨（同rigour）',
  'RINSE',
  'v. & n. 冲洗；漂洗',
  'RIOT',
  'n. & v. 暴乱；骚乱',
  'RIPPLE',
  'n. 涟漪；波纹',
  'RITUAL',
  'n. 仪式；典礼',
  'RIVAL',
  'n. 对手；竞争者',
  'RIVALRY',
  'n. 竞争；敌对',
  'ROAM',
  'v. 漫步；闲逛',
  'ROBBERY',
  'n. 抢劫；盗窃',
  'ROBUST',
  'adj. 强壮的；稳健的',
  'ROMANCE',
  'n. 浪漫；恋爱；传奇',
  'ROTARY',
  'adj. 旋转的；转动的',
  'ROTATE',
  'v. 旋转；轮流',
  'ROYALTY',
  'n. 皇室；版税；特许权',
  'RUBY',
  'n. 红宝石；红宝石色',
  'RULING',
  'n. 裁决；统治',
  'RUMOUR',
  'n. 谣言；传闻',
  'RUPTURE',
  'n. & v. 破裂；断裂',
  'SALMON',
  'n. 鲑鱼；三文鱼',
  'SAMPLE',
  'n. 样本；样品',
  'SARDINE',
  'n. 沙丁鱼',
  'SATIRE',
  'n. 讽刺；讽刺作品',
  'SATURN',
  'n. 土星',
  'SCALD',
  'v. 烫伤；烫洗',
  'SCANDAL',
  'n. 丑闻；丑事',
  'SCARLET',
  'adj. 猩红的；鲜红的',
  'SCATTER',
  'v. 散开；散布',
  'SCENT',
  'n. 气味；香味；线索',
  'SCHEME',
  'n. 计划；方案；阴谋',
  'SCOFF',
  'v. & n. 嘲笑；嘲弄',
  'SCOOP',
  'n. 勺子；独家新闻',
  'SCOPE',
  'n. 范围；领域；机会',
  'SCORCH',
  'v. 烧焦；烤焦',
  'SCORN',
  'v. & n. 轻蔑；鄙视',
  'SCOUT',
  'n. 侦察员；童子军',
  'SCRAP',
  'n. 碎片；废料',
  'SCRAPE',
  'v. 刮擦；勉强通过',
  'SCREW',
  'n. 螺丝钉；螺旋',
  'SCRIPT',
  'n. 脚本；剧本；文字',
  'SCRUB',
  'v. 擦洗；取消',
  'SEAM',
  'n. 接缝；煤层',
  'SEAPORT',
  'n. 海港；港口城市',
  'SEASICK',
  'adj. 晕船的',
  'SECTOR',
  'n. 部门；区域；扇形',
  'SEMINAR',
  'n. 研讨会；研习班',
  'SENATOR',
  'n. 参议员',
  'SENSOR',
  'n. 传感器；探测器',
  'SERIAL',
  'adj. 连续的；连载的',
  'SERIES',
  'n. 系列；连续',
  'SERMON',
  'n. 布道；说教',
  'SERPENT',
  'n. 蛇',
  'SETBACK',
  'n. 挫折；倒退',
  'SEXISM',
  'n. 性别歧视',
  'SHADOWY',
  'adj. 多阴影的；模糊的',
  'SHAFT',
  'n. 轴；杆；矿井',
  'SHAM',
  'n. 假冒；赝品',
  'SHAMPOO',
  'n. 洗发水',
  'SHATTER',
  'v. 粉碎；破坏',
  'SHED',
  'v. 脱落；流出',
  'SHEER',
  'adj. 纯粹的；陡峭的',
  'SHELL',
  'n. 壳；炮弹；外壳',
  'SHERIFF',
  'n. 警长；治安官',
  'SHIELD',
  'n. 盾牌；防护物',
  'SHIFT',
  'v. & n. 转移；改变；轮班',
  'SHIVER',
  'v. & n. 颤抖；哆嗦',
  'SHOVE',
  'v. 推；挤',
  'SHOVEL',
  'n. 铲子',
  'SHREWD',
  'adj. 精明的；机敏的',
  'SHRIMP',
  'n. 虾；小虾',
  'SHRINE',
  'n. 神殿；神龛',
  'SHRUG',
  'v. & n. 耸肩',
  'SHRUB',
  'n. 灌木',
  'SHUDDER',
  'v. & n. 战栗；发抖',
  'SHUFFLE',
  'v. 拖着脚走；洗牌',
  'SHUNT',
  'v. 使分流；调车',
  'SHUTTER',
  'n. 百叶窗；快门',
  'SIEVE',
  'n. 筛子',
  'SIFT',
  'v. 筛选；详查',
  'SIGNIFY',
  'v. 表示；意味',
  'SILICON',
  'n. 硅',
  'SILT',
  'n. 淤泥；泥沙',
  'SIREN',
  'n. 警报器；警笛',
  'SKETCH',
  'n. 素描；概略',
  'SLACK',
  'adj. 松弛的；懈怠的',
  'SLANDER',
  'v. & n. 诽谤；中伤',
  'SLANG',
  'n. 俚语；行话',
  'SLAP',
  'v. & n. 掌掴；拍打',
  'SLASH',
  'v. 砍；大幅削减',
  'SLENDER',
  'adj. 纤细的；苗条的',
  'SLICK',
  'adj. 光滑的；花言巧语的',
  'SLIT',
  'v. 切开；撕裂',
  'SLOGAN',
  'n. 口号；标语',
  'SLOT',
  'n. 槽；狭缝；时间档',
  'SLUM',
  'n. 贫民窟',
  'SLUMBER',
  'v. & n. 睡眠；沉睡',
  'SLUMP',
  'v. & n. 暴跌；瘫倒',
  'SLUR',
  'v. 含糊地说；诽谤',
  'SMASH',
  'v. & n. 粉碎；猛撞',
  'SMUGGLE',
  'v. 走私；偷运',
  'SNAIL',
  'n. 蜗牛',
  'SNAP',
  'v. 折断；拍照',
  'SNEAK',
  'v. 偷偷地走；潜行',
  'SNEER',
  'v. & n. 嘲笑；讥讽',
  'SNOB',
  'n. 势利的人；自命不凡的人',
  'SOAR',
  'v. 飞翔；猛增',
  'SOBER',
  'adj. 清醒的；冷静的',
  'SODIUM',
  'n. 钠',
  'SOFTEN',
  'v. 软化；变柔和',
  'SOLEMN',
  'adj. 庄严的；严肃的',
  'SOLO',
  'n. & adj. 独奏；独唱；单人的',
  'SOLUBLE',
  'adj. 可溶的；可解决的',
  'SOLVENT',
  'n. 溶剂',
  'SPAN',
  'n. 跨度；持续期间',
  'SPARK',
  'n. 火花；火星',
  'SPARKLE',
  'v. 闪耀；闪烁',
  'SPATIAL',
  'adj. 空间的；与空间有关的',
  'SPECIES',
  'n. 物种；种类',
  'SPICE',
  'n. 香料；调味品',
  'SPIDER',
  'n. 蜘蛛',
  'SPILL',
  'v. 溢出；洒落',
  'SPINE',
  'n. 脊柱；脊骨；书脊',
  'SPIRAL',
  'adj. 螺旋的',
  'SPITE',
  'n. 恶意；怨恨',
  'SPLASH',
  'v. 溅；泼',
  'SPOIL',
  'v. 宠坏；破坏；变质',
  'SPONGE',
  'n. 海绵',
  'SPOUSE',
  'n. 配偶',
  'SQUAD',
  'n. 班；小队',
  'SQUALOR',
  'n. 肮脏；邋遢',
  'SQUASH',
  'v. 压扁；挤压',
  'SQUAT',
  'v. 蹲；蹲坐',
  'STAB',
  'v. & n. 刺；捅',
  'STACK',
  'n. 堆；堆叠',
  'STAGGER',
  'v. 蹒跚；交错',
  'STALL',
  'n. 摊位；畜栏',
  'STAMMER',
  'v. & n. 口吃；结巴',
  'STAPLE',
  'n. 订书钉；主食',
  'STARK',
  'adj. 明显的；荒凉的',
  'STARTLE',
  'v. 使惊吓；使吃惊',
  'STEM',
  'n. 茎；主干',
  'STEREO',
  'n. 立体声；立体声音响',
  'STERN',
  'adj. 严厉的；坚定的',
  'STEW',
  'v. & n. 炖；焖',
  'STIFF',
  'adj. 僵硬的；严厉的',
  'STING',
  'v. & n. 刺；蛰；刺痛',
  'STIR',
  'v. 搅拌；激起',
  'STITCH',
  'n. 针脚；缝线',
  'STOCK',
  'n. 库存；股份',
  'STOOL',
  'n. 凳子；粪便',
  'STOOP',
  'v. 弯腰；屈尊',
  'STRAIN',
  'v. & n. 拉紧；紧张；压力',
  'STRAND',
  'n. 股；缕；海滨',
  'STRAP',
  'n. 带子；皮带',
  'STREAK',
  'n. 条纹；一连串',
  'STRETCH',
  'v. & n. 伸展；延伸',
  'STRIDE',
  'v. & n. 大步走；迈步',
  'STRIFE',
  'n. 冲突；争斗',
  'STRIP',
  'v. 剥去；拆除',
  'STRIPE',
  'n. 条纹；斑纹',
  'STRIVE',
  'v. 努力；奋斗',
  'STROKE',
  'n. 打击；中风；笔画',
  'STROLL',
  'v. & n. 散步；漫步',
  'STUFFY',
  'adj. 通风不良的；闷热的',
  'STUMBLE',
  'v. 绊倒；结巴',
  'STUMP',
  'n. 树桩；残肢',
  'STUN',
  'v. 使震惊；使昏迷',
  'STURDY',
  'adj. 结实的；坚固的',
  'SUBDUE',
  'v. 征服；制服',
  'SUBSIDY',
  'n. 补贴；补助金',
  'SUBTLE',
  'adj. 微妙的；细微的',
  'SUBURB',
  'n. 郊区',
  'SUFFICE',
  'v. 足够；满足',
  'SUICIDE',
  'n. 自杀',
  'SULLEN',
  'adj. 闷闷不乐的；阴沉的',
  'SULPHUR',
  'n. 硫磺（同sulfur）',
  'SUMMIT',
  'n. 顶峰；峰会',
  'SUMMON',
  'v. 召唤；召集',
  'SURGE',
  'v. & n. 汹涌；激增',
  'SURGERY',
  'n. 外科手术；诊所',
  'SURVEY',
  'v. & n. 调查；测量',
  'SUSPEND',
  'v. 暂停；悬挂',
  'SUSTAIN',
  'v. 维持；支撑',
  'SWAMP',
  'n. 沼泽；湿地',
  'SWAY',
  'v. 摇摆；影响',
  'SWEETEN',
  'v. 使变甜；缓和',
  'TACK',
  'n. 图钉；方针',
  'TACKLE',
  'v. 解决；应对',
  'TACT',
  'n. 机智；老练',
  'TACTICS',
  'n. 策略；战术',
  'TAME',
  'a. 驯服的，温顺的',
  'TANGLE',
  'v. 缠结，纠缠',
  'TAPER',
  'v. 逐渐变细',
  'TARIFF',
  'n. 关税',
  'TEDIOUS',
  'a. 冗长乏味的，单调的，令人厌烦的',
  'TEMPER',
  'n. 脾气，情绪',
  'TEMPO',
  'n. （音乐的）速度，拍子',
  'TEMPT',
  'v. 引诱，诱惑',
  'TENANT',
  'n. 房客，租户',
  'TENDER',
  'a. 温柔的',
  'TENSILE',
  'a. 张力的，拉力的',
  'TERRACE',
  'n. 露台，阳台',
  'TERRAIN',
  'n. 地形，地势',
  'TESTIFY',
  'v. 作证，证明',
  'TEXTURE',
  'n. 质地，纹理',
  'THEOREM',
  'n. 定理，原理',
  'THERAPY',
  'n. 治疗，疗法',
  'THEREBY',
  'ad. 从而，借此',
  'THEREIN',
  'ad. 在其中，在那方面',
  'THEREOF',
  'ad. 它的，其，由其',
  'THERMAL',
  'a. 热的，热量的',
  'THESIS',
  'n. 论文，毕业论文',
  'THICKEN',
  'v. （使）变厚，（使）变粗，（使）变浓',
  'THIGH',
  'n. 大腿',
  'THORN',
  'n. 刺，荆棘',
  'THRASH',
  'v. 痛打，鞭笞',
  'THREAT',
  'n. 威胁，恐吓',
  'THRIFT',
  'n. 节俭，节约',
  'THRIFTY',
  'a. 节俭的，节约的',
  'THRIVE',
  'v. 兴旺，繁荣',
  'THRONE',
  'n. 王位，王座',
  'THRUST',
  'v. 猛推，刺，戳',
  'THUMB',
  'n. 大拇指',
  'TICKLE',
  'v. 挠痒，使发痒',
  'TIDE',
  'n. 潮汐，潮水',
  'TIGHTEN',
  'v. （使）变紧，加固',
  'TILE',
  'n. 瓦片，瓷砖',
  'TILT',
  'v. （使）倾斜，歪斜',
  'TIMELY',
  'a. 及时的，适时的',
  'TIMID',
  'a. 胆小的，羞怯的',
  'TOAD',
  'n. 蟾蜍，癞蛤蟆',
  'TOLL',
  'n. 过路费',
  'TONE',
  'n. 音调，语调',
  'TORMENT',
  'n. 痛苦，折磨',
  'TORPEDO',
  'n. 鱼雷',
  'TORQUE',
  'n. 转矩，扭矩',
  'TOSS',
  'v. 扔，抛',
  'TOWARDS',
  'prep. 朝，向',
  'TOXIC',
  'a. 有毒的',
  'TRACE',
  'v. 追踪，追溯',
  'TRACT',
  'n. 大片土地，地带',
  'TRADER',
  'n. 商人，交易员',
  'TRAGEDY',
  'n. 悲剧',
  'TRAGIC',
  'a. 悲剧的，悲惨的',
  'TRAIL',
  'n. 痕迹，足迹',
  'TRAIT',
  'n. 特征，特点，特性',
  'TRAMP',
  'n. 流浪汉',
  'TRAMPLE',
  'v. 践踏，踩坏',
  'TRANSIT',
  'n. 运输，运送',
  'TRASH',
  'n. 垃圾，废物',
  'TREATY',
  'n. 条约，协定',
  'TRENCH',
  'n. 沟，壕沟',
  'TRIBAL',
  'a. 部落的，部族的',
  'TRIBE',
  'n. 部落，部族',
  'TRIBUTE',
  'n. 致敬，颂词',
  'TRIFLE',
  'n. 琐事，小事',
  'TRIGGER',
  'n. 扳机',
  'TRIM',
  'v. 修剪，整理',
  'TRIPLE',
  'a. 三倍的，三重的',
  'TRIUMPH',
  'n. 胜利，巨大成功',
  'TRIVIAL',
  'a. 琐碎的，不重要的',
  'TROLLEY',
  'n. 手推车，购物车',
  'TROT',
  'v. 快步走，小跑；（使）小跑',
  'TRUMPET',
  'n. 喇叭，小号；（象的）吼叫声',
  'TUCK',
  'v. 卷起；塞进；把...藏起来',
  'TUITION',
  'n. 学费；教学，讲授',
  'TULIP',
  'n. 郁金香',
  'TUMBLE',
  'v. 跌倒，摔跤；暴跌；翻滚',
  'TUNA',
  'n. 金枪鱼',
  'TUNNEL',
  'n. 地道，隧道',
  'TURTLE',
  'n. 海龟，乌龟',
  'TYRANNY',
  'n. 暴政，专制；暴行',
  'TYRANT',
  'n. 暴君；专制君主',
  'UNEASY',
  'a. 心神不宁的，不安的；不稳定的',
  'UNEVEN',
  'a. 不平坦的；不均匀的；不对等的',
  'UNIFY',
  'v. 统一，使联合；使一致',
  'UNIFIED',
  'a. 统一的，联合的',
  'UNITED',
  'a. 联合的，团结的；一致的',
  'UNITY',
  'n. 团结；一致；整体',
  'UNJUST',
  'a. 不公平的，不义的',
  'UNKIND',
  'a. 不仁慈的，刻薄的，冷酷的',
  'UNLOCK',
  'v. 开锁；释放；揭开（秘密）',
  'UNPAID',
  'a. 未付的；无报酬的，志愿的',
  'UNTIE',
  'v. 解开，松开；释放',
  'UNWRAP',
  'v. 打开，拆开（包装）',
  'UPDATE',
  'v. 更新；提供最新消息',
  'UPGRADE',
  'v. 升级；提升；改善',
  'UPHOLD',
  'v. 维护，支持；维持（原判）',
  'UPRIGHT',
  'a. 垂直的，直立的；正直的',
  'UPROAR',
  'n. 喧嚣，轰动；骚动',
  'USAGE',
  'n. 使用，用法；习惯；虐待',
  'UTENSIL',
  'n. 器具，器皿；用具',
  'UTILIZE',
  'v. 利用，使用',
  'UTMOST',
  'a. 极度的；最远的',
  'UTOPIAN',
  'a. 乌托邦式的，空想的',
  'UTTERLY',
  'ad. 完全地，彻底地',
  'VACUUM',
  'n. 真空；空间；真空吸尘器',
  'VALVE',
  'n. 阀，阀门；（心脏的）瓣膜',
  'VANISH',
  'v. 消失，灭绝；化为乌有',
  'VANITY',
  'n. 虚荣心；浮华；虚无',
  'VAPOUR',
  'n. 蒸气；水汽',
  'VAULT',
  'n. 金库，保险库；地下墓穴；拱顶',
  'VECTOR',
  'n. [数] 向量，矢量；（疾病的）传病媒介',
  'VEIL',
  'n. 面纱；掩饰，遮盖物',
  'VEIN',
  'n. 静脉；血管；叶脉；纹理；矿脉',
  'VELVET',
  'n. 天鹅绒，丝绒',
  'VENT',
  'n. 通风口，排气口；（情感的）发泄口',
  'VENUS',
  'n. 金星；维纳斯（爱与美之神）',
  'VERDICT',
  'n. （陪审团的）裁决，判决；舆论，定论',
  'VERGE',
  'n. 边缘，边界',
  'VERIFY',
  'v. 核实，查证；证实',
  'VERSE',
  'n. 诗，韵文；诗节，诗行',
  'VERSUS',
  'prep. 诉，对抗；与...相对（通常缩写为 vs.）',
  'VESSEL',
  'n. 船只，大船；容器；血管',
  'VETERAN',
  'n. 退伍军人，老兵；老手，经验丰富者',
  'VETO',
  'n. 否决权；禁止',
  'VIBRATE',
  'v. （使）振动，（使）摇摆；共鸣',
  'VICIOUS',
  'a. 恶毒的，凶残的；恶性的',
  'VIGOUR',
  'n. 活力，精力；气势（美式拼写为 vigor）',
  'VILLA',
  'n. 别墅；郊区住宅',
  'VINE',
  'n. 葡萄藤；蔓生植物',
  'VIRGIN',
  'n. 处女',
  'VIRTUAL',
  'a. 虚拟的；实质上的，事实上的',
  'VISIBLE',
  'a. 可见的；明显的',
  'VISION',
  'n. 视力；远见，眼光；幻象',
  'VITAMIN',
  'n. 维生素',
  'VOCAL',
  'a. 声音的，嗓音的；大声表达意见的',
  'VOID',
  'a. 无效的；缺乏的',
  'VOWEL',
  'n. 元音；元音字母',
  'VULGAR',
  'a. 庸俗的，粗俗的；通俗的',
  'WADE',
  'v. 涉水，涉泥地；艰难地通过',
  'WAGON',
  'n. 货运马车，四轮运货马车（旧拼写为 waggon）',
  'WAKEN',
  'v. 醒来；唤醒；激起',
  'WARE',
  'n. 制品，器皿；商品，货物',
  'WARFARE',
  'n. 战争，作战；冲突，斗争',
  'WARRANT',
  'n. 授权证，令状；根据',
  'WASP',
  'n. 黄蜂，胡蜂',
  'WATERY',
  'a. 水汪汪的；掺水的，稀薄的',
  'WATT',
  'n. 瓦特（功率单位）',
  'WEARY',
  'a. 疲惫的；令人厌烦的',
  'WEAVER',
  'n. 织布工，编织者',
  'WEDGE',
  'n. 楔子；楔形物',
  'WEIRD',
  'a. 怪异的，神秘的；荒唐的',
  'WHARF',
  'n. 码头，停泊处',
  'WHEREAS',
  'conj. 然而，反之，鉴于',
  'WHEREBY',
  'ad. 凭此，借以；由于',
  'WHILST',
  'conj. 同时；然而；虽然（主要用于英式英语）',
  'WHIRL',
  'v. 旋转，急转；（头）晕',
  'WICKED',
  'a. 邪恶的，恶劣的；淘气的',
  'WIDOW',
  'n. 寡妇',
  'WIDTH',
  'n. 宽度，广度',
  'WIELD',
  'v. 挥舞（武器）；行使，掌管（权力等）',
  'WILLOW',
  'n. 柳树，柳木',
  'WINDING',
  'a. 蜿蜒的，迂回的；卷绕的',
  'WINK',
  'v. 眨眼；闪烁',
  'WITHER',
  'v. 枯萎，凋谢；衰退',
  'WITTY',
  'a. 机智幽默的，妙趣横生的',
  'WORLDLY',
  'a. 世俗的，尘世的；老练的',
  'WORSHIP',
  'n. 崇拜；礼拜'
]

module.exports = wordList